// Code generated by protoc-gen-go. DO NOT EDIT.
// source: minion.proto

package minion

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetNamespaces struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGetNamespaces) Reset()         { *m = QueryGetNamespaces{} }
func (m *QueryGetNamespaces) String() string { return proto.CompactTextString(m) }
func (*QueryGetNamespaces) ProtoMessage()    {}
func (*QueryGetNamespaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{0}
}

func (m *QueryGetNamespaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGetNamespaces.Unmarshal(m, b)
}
func (m *QueryGetNamespaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGetNamespaces.Marshal(b, m, deterministic)
}
func (m *QueryGetNamespaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNamespaces.Merge(m, src)
}
func (m *QueryGetNamespaces) XXX_Size() int {
	return xxx_messageInfo_QueryGetNamespaces.Size(m)
}
func (m *QueryGetNamespaces) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNamespaces.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNamespaces proto.InternalMessageInfo

func (m *QueryGetNamespaces) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *QueryGetNamespaces) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type QueryDatabase struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDatabase) Reset()         { *m = QueryDatabase{} }
func (m *QueryDatabase) String() string { return proto.CompactTextString(m) }
func (*QueryDatabase) ProtoMessage()    {}
func (*QueryDatabase) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{1}
}

func (m *QueryDatabase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDatabase.Unmarshal(m, b)
}
func (m *QueryDatabase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDatabase.Marshal(b, m, deterministic)
}
func (m *QueryDatabase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDatabase.Merge(m, src)
}
func (m *QueryDatabase) XXX_Size() int {
	return xxx_messageInfo_QueryDatabase.Size(m)
}
func (m *QueryDatabase) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDatabase.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDatabase proto.InternalMessageInfo

func (m *QueryDatabase) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

type QueryGetTables struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGetTables) Reset()         { *m = QueryGetTables{} }
func (m *QueryGetTables) String() string { return proto.CompactTextString(m) }
func (*QueryGetTables) ProtoMessage()    {}
func (*QueryGetTables) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{2}
}

func (m *QueryGetTables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGetTables.Unmarshal(m, b)
}
func (m *QueryGetTables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGetTables.Marshal(b, m, deterministic)
}
func (m *QueryGetTables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTables.Merge(m, src)
}
func (m *QueryGetTables) XXX_Size() int {
	return xxx_messageInfo_QueryGetTables.Size(m)
}
func (m *QueryGetTables) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTables.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTables proto.InternalMessageInfo

func (m *QueryGetTables) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

type QueryScheduleBackup struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryScheduleBackup) Reset()         { *m = QueryScheduleBackup{} }
func (m *QueryScheduleBackup) String() string { return proto.CompactTextString(m) }
func (*QueryScheduleBackup) ProtoMessage()    {}
func (*QueryScheduleBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{3}
}

func (m *QueryScheduleBackup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryScheduleBackup.Unmarshal(m, b)
}
func (m *QueryScheduleBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryScheduleBackup.Marshal(b, m, deterministic)
}
func (m *QueryScheduleBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryScheduleBackup.Merge(m, src)
}
func (m *QueryScheduleBackup) XXX_Size() int {
	return xxx_messageInfo_QueryScheduleBackup.Size(m)
}
func (m *QueryScheduleBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryScheduleBackup.DiscardUnknown(m)
}

var xxx_messageInfo_QueryScheduleBackup proto.InternalMessageInfo

func (m *QueryScheduleBackup) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *QueryScheduleBackup) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *QueryScheduleBackup) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *QueryScheduleBackup) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type QueryStartBackup struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStartBackup) Reset()         { *m = QueryStartBackup{} }
func (m *QueryStartBackup) String() string { return proto.CompactTextString(m) }
func (*QueryStartBackup) ProtoMessage()    {}
func (*QueryStartBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{4}
}

func (m *QueryStartBackup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStartBackup.Unmarshal(m, b)
}
func (m *QueryStartBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStartBackup.Marshal(b, m, deterministic)
}
func (m *QueryStartBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStartBackup.Merge(m, src)
}
func (m *QueryStartBackup) XXX_Size() int {
	return xxx_messageInfo_QueryStartBackup.Size(m)
}
func (m *QueryStartBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStartBackup.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStartBackup proto.InternalMessageInfo

func (m *QueryStartBackup) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *QueryStartBackup) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *QueryStartBackup) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type Namespaces struct {
	Names                []string  `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Sizes                []string  `protobuf:"bytes,2,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Ok                   []float64 `protobuf:"fixed64,3,rep,packed,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Namespaces) Reset()         { *m = Namespaces{} }
func (m *Namespaces) String() string { return proto.CompactTextString(m) }
func (*Namespaces) ProtoMessage()    {}
func (*Namespaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{5}
}

func (m *Namespaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespaces.Unmarshal(m, b)
}
func (m *Namespaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespaces.Marshal(b, m, deterministic)
}
func (m *Namespaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespaces.Merge(m, src)
}
func (m *Namespaces) XXX_Size() int {
	return xxx_messageInfo_Namespaces.Size(m)
}
func (m *Namespaces) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespaces.DiscardUnknown(m)
}

var xxx_messageInfo_Namespaces proto.InternalMessageInfo

func (m *Namespaces) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Namespaces) GetSizes() []string {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *Namespaces) GetOk() []float64 {
	if m != nil {
		return m.Ok
	}
	return nil
}

type Tables struct {
	Tables               []*Tables_TableUnit `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Tables) Reset()         { *m = Tables{} }
func (m *Tables) String() string { return proto.CompactTextString(m) }
func (*Tables) ProtoMessage()    {}
func (*Tables) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{6}
}

func (m *Tables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tables.Unmarshal(m, b)
}
func (m *Tables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tables.Marshal(b, m, deterministic)
}
func (m *Tables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tables.Merge(m, src)
}
func (m *Tables) XXX_Size() int {
	return xxx_messageInfo_Tables.Size(m)
}
func (m *Tables) XXX_DiscardUnknown() {
	xxx_messageInfo_Tables.DiscardUnknown(m)
}

var xxx_messageInfo_Tables proto.InternalMessageInfo

func (m *Tables) GetTables() []*Tables_TableUnit {
	if m != nil {
		return m.Tables
	}
	return nil
}

type Tables_TableUnit struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LastBackup           string   `protobuf:"bytes,2,opt,name=lastBackup,proto3" json:"lastBackup,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tables_TableUnit) Reset()         { *m = Tables_TableUnit{} }
func (m *Tables_TableUnit) String() string { return proto.CompactTextString(m) }
func (*Tables_TableUnit) ProtoMessage()    {}
func (*Tables_TableUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{6, 0}
}

func (m *Tables_TableUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tables_TableUnit.Unmarshal(m, b)
}
func (m *Tables_TableUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tables_TableUnit.Marshal(b, m, deterministic)
}
func (m *Tables_TableUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tables_TableUnit.Merge(m, src)
}
func (m *Tables_TableUnit) XXX_Size() int {
	return xxx_messageInfo_Tables_TableUnit.Size(m)
}
func (m *Tables_TableUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_Tables_TableUnit.DiscardUnknown(m)
}

var xxx_messageInfo_Tables_TableUnit proto.InternalMessageInfo

func (m *Tables_TableUnit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tables_TableUnit) GetLastBackup() string {
	if m != nil {
		return m.LastBackup
	}
	return ""
}

func (m *Tables_TableUnit) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type Backups struct {
	Backups              []string `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Backups) Reset()         { *m = Backups{} }
func (m *Backups) String() string { return proto.CompactTextString(m) }
func (*Backups) ProtoMessage()    {}
func (*Backups) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{7}
}

func (m *Backups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backups.Unmarshal(m, b)
}
func (m *Backups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backups.Marshal(b, m, deterministic)
}
func (m *Backups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backups.Merge(m, src)
}
func (m *Backups) XXX_Size() int {
	return xxx_messageInfo_Backups.Size(m)
}
func (m *Backups) XXX_DiscardUnknown() {
	xxx_messageInfo_Backups.DiscardUnknown(m)
}

var xxx_messageInfo_Backups proto.InternalMessageInfo

func (m *Backups) GetBackups() []string {
	if m != nil {
		return m.Backups
	}
	return nil
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_70d86c67c629e4a9, []int{8}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryGetNamespaces)(nil), "minion.QueryGetNamespaces")
	proto.RegisterType((*QueryDatabase)(nil), "minion.QueryDatabase")
	proto.RegisterType((*QueryGetTables)(nil), "minion.QueryGetTables")
	proto.RegisterType((*QueryScheduleBackup)(nil), "minion.QueryScheduleBackup")
	proto.RegisterType((*QueryStartBackup)(nil), "minion.QueryStartBackup")
	proto.RegisterType((*Namespaces)(nil), "minion.Namespaces")
	proto.RegisterType((*Tables)(nil), "minion.Tables")
	proto.RegisterType((*Tables_TableUnit)(nil), "minion.Tables.TableUnit")
	proto.RegisterType((*Backups)(nil), "minion.Backups")
	proto.RegisterType((*Response)(nil), "minion.Response")
}

func init() { proto.RegisterFile("minion.proto", fileDescriptor_70d86c67c629e4a9) }

var fileDescriptor_70d86c67c629e4a9 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0xf5, 0xc7, 0x9d, 0x0f, 0xcf, 0x71, 0xc6, 0x1a, 0x0e, 0xb4, 0x32, 0x08, 0xac, 0xa5, 0xb9,
	0xea, 0x84, 0x82, 0xa0, 0x80, 0x2a, 0x01, 0x29, 0x34, 0x20, 0x61, 0x08, 0x1d, 0xc5, 0x3a, 0x59,
	0x81, 0x95, 0xf8, 0x43, 0xd9, 0x8d, 0x10, 0xfc, 0x13, 0x7e, 0x2d, 0xc8, 0xfb, 0x11, 0x67, 0x1d,
	0x1a, 0xc4, 0x55, 0xd9, 0x79, 0x6f, 0xde, 0x8c, 0xdf, 0xcc, 0x28, 0x70, 0xbb, 0xae, 0x9a, 0xaa,
	0x6d, 0xae, 0xbb, 0x6d, 0x2b, 0x5b, 0x8c, 0x74, 0x44, 0x67, 0x80, 0x1f, 0x76, 0x7c, 0xfb, 0x63,
	0xce, 0xe5, 0x7b, 0x56, 0x73, 0xd1, 0xb1, 0x25, 0x17, 0x98, 0x40, 0xb0, 0x2a, 0x89, 0x9f, 0xfb,
	0x57, 0x71, 0x11, 0xac, 0x4a, 0x7c, 0x08, 0x71, 0x63, 0x59, 0x12, 0x28, 0x78, 0x00, 0xe8, 0x63,
	0xb8, 0x50, 0x35, 0xde, 0x30, 0xc9, 0x4a, 0x26, 0xf8, 0x58, 0x4e, 0x73, 0x48, 0x6c, 0x93, 0x4f,
	0xac, 0xdc, 0x1c, 0x37, 0xa0, 0xdf, 0xe1, 0xae, 0xca, 0xf8, 0xb8, 0xfc, 0xc6, 0x57, 0xbb, 0x0d,
	0x9f, 0xb1, 0xe5, 0x7a, 0xd7, 0xfd, 0xdb, 0x77, 0xe0, 0x25, 0x9c, 0xca, 0xbe, 0x3c, 0x09, 0x15,
	0xa3, 0x83, 0x5e, 0x23, 0xab, 0x9a, 0x0b, 0xc9, 0xea, 0x8e, 0x9c, 0x68, 0xcd, 0x1e, 0xa0, 0x9f,
	0x21, 0xd5, 0x8d, 0x25, 0xdb, 0xca, 0x9b, 0xeb, 0x4a, 0xdf, 0x02, 0x1c, 0xcc, 0xf3, 0x12, 0x4e,
	0x95, 0x80, 0xf8, 0x79, 0xd8, 0xe7, 0xa8, 0xa0, 0x47, 0x45, 0xf5, 0x93, 0x0b, 0x12, 0x68, 0x54,
	0x05, 0x7d, 0xf7, 0x76, 0x4d, 0xc2, 0x3c, 0xbc, 0xf2, 0x8b, 0xa0, 0x5d, 0xd3, 0x5f, 0x3e, 0x44,
	0x66, 0x6a, 0x4f, 0x21, 0x52, 0xd5, 0x75, 0x9d, 0xf3, 0x09, 0xb9, 0x36, 0x3b, 0xd5, 0xbc, 0xfe,
	0x59, 0x34, 0x95, 0x2c, 0x4c, 0x5e, 0xf6, 0x05, 0xe2, 0x3d, 0x88, 0x08, 0x27, 0x7d, 0x63, 0xe3,
	0x4c, 0xbd, 0xf1, 0x11, 0xc0, 0x86, 0x09, 0xe3, 0xdc, 0x98, 0x3b, 0x40, 0x5c, 0xef, 0xe1, 0x78,
	0xf3, 0x4f, 0xe0, 0x4c, 0xe7, 0x09, 0x24, 0x70, 0x56, 0xea, 0xa7, 0x31, 0x69, 0x43, 0xfa, 0x12,
	0x6e, 0x15, 0x5c, 0x74, 0x6d, 0x23, 0x38, 0xa6, 0x10, 0xd6, 0xe2, 0xab, 0xf9, 0x82, 0xfe, 0xe9,
	0xae, 0x27, 0x18, 0xad, 0x67, 0xf2, 0x3b, 0x80, 0xe8, 0x9d, 0xf2, 0x88, 0x53, 0xb8, 0x70, 0x8f,
	0x34, 0xb3, 0xee, 0x8f, 0x0f, 0x38, 0x43, 0xcb, 0x0d, 0x18, 0xf5, 0xf0, 0x39, 0xc4, 0xc3, 0x09,
	0xde, 0x1f, 0xcb, 0x35, 0x9e, 0x25, 0xee, 0x50, 0xa9, 0x87, 0x2f, 0x00, 0xe6, 0x5c, 0x5a, 0xa3,
	0xf7, 0x1c, 0x9d, 0xbd, 0xf9, 0xec, 0x8e, 0x85, 0x4d, 0x1e, 0xf5, 0x70, 0x0a, 0xc9, 0xe8, 0x9e,
	0x1f, 0x38, 0x5a, 0x97, 0xcc, 0x52, 0x4b, 0xda, 0x69, 0x51, 0x0f, 0x5f, 0x43, 0xba, 0x68, 0xc4,
	0x7f, 0x16, 0x79, 0x05, 0xe7, 0x87, 0xe7, 0x4d, 0x5c, 0xfd, 0xc0, 0xfc, 0x4d, 0x5c, 0x46, 0xea,
	0xff, 0xe2, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x00, 0x4f, 0x62, 0x3f, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MinionClient is the client API for Minion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MinionClient interface {
	GetNamespaces(ctx context.Context, in *QueryGetNamespaces, opts ...grpc.CallOption) (*Namespaces, error)
	GetTables(ctx context.Context, in *QueryGetTables, opts ...grpc.CallOption) (*Tables, error)
	GetBackups(ctx context.Context, in *QueryDatabase, opts ...grpc.CallOption) (*Backups, error)
	ScheduleBackup(ctx context.Context, in *QueryScheduleBackup, opts ...grpc.CallOption) (*Response, error)
	UnscheduleBackup(ctx context.Context, in *QueryScheduleBackup, opts ...grpc.CallOption) (*Response, error)
	StartBackup(ctx context.Context, in *QueryStartBackup, opts ...grpc.CallOption) (*Response, error)
}

type minionClient struct {
	cc *grpc.ClientConn
}

func NewMinionClient(cc *grpc.ClientConn) MinionClient {
	return &minionClient{cc}
}

func (c *minionClient) GetNamespaces(ctx context.Context, in *QueryGetNamespaces, opts ...grpc.CallOption) (*Namespaces, error) {
	out := new(Namespaces)
	err := c.cc.Invoke(ctx, "/minion.Minion/GetNamespaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) GetTables(ctx context.Context, in *QueryGetTables, opts ...grpc.CallOption) (*Tables, error) {
	out := new(Tables)
	err := c.cc.Invoke(ctx, "/minion.Minion/GetTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) GetBackups(ctx context.Context, in *QueryDatabase, opts ...grpc.CallOption) (*Backups, error) {
	out := new(Backups)
	err := c.cc.Invoke(ctx, "/minion.Minion/GetBackups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) ScheduleBackup(ctx context.Context, in *QueryScheduleBackup, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/minion.Minion/ScheduleBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) UnscheduleBackup(ctx context.Context, in *QueryScheduleBackup, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/minion.Minion/UnscheduleBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) StartBackup(ctx context.Context, in *QueryStartBackup, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/minion.Minion/StartBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinionServer is the server API for Minion service.
type MinionServer interface {
	GetNamespaces(context.Context, *QueryGetNamespaces) (*Namespaces, error)
	GetTables(context.Context, *QueryGetTables) (*Tables, error)
	GetBackups(context.Context, *QueryDatabase) (*Backups, error)
	ScheduleBackup(context.Context, *QueryScheduleBackup) (*Response, error)
	UnscheduleBackup(context.Context, *QueryScheduleBackup) (*Response, error)
	StartBackup(context.Context, *QueryStartBackup) (*Response, error)
}

func RegisterMinionServer(s *grpc.Server, srv MinionServer) {
	s.RegisterService(&_Minion_serviceDesc, srv)
}

func _Minion_GetNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNamespaces)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).GetNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minion.Minion/GetNamespaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).GetNamespaces(ctx, req.(*QueryGetNamespaces))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minion_GetTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTables)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).GetTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minion.Minion/GetTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).GetTables(ctx, req.(*QueryGetTables))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minion_GetBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDatabase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).GetBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minion.Minion/GetBackups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).GetBackups(ctx, req.(*QueryDatabase))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minion_ScheduleBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryScheduleBackup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).ScheduleBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minion.Minion/ScheduleBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).ScheduleBackup(ctx, req.(*QueryScheduleBackup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minion_UnscheduleBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryScheduleBackup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).UnscheduleBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minion.Minion/UnscheduleBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).UnscheduleBackup(ctx, req.(*QueryScheduleBackup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minion_StartBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStartBackup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).StartBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minion.Minion/StartBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).StartBackup(ctx, req.(*QueryStartBackup))
	}
	return interceptor(ctx, in, info, handler)
}

var _Minion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "minion.Minion",
	HandlerType: (*MinionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNamespaces",
			Handler:    _Minion_GetNamespaces_Handler,
		},
		{
			MethodName: "GetTables",
			Handler:    _Minion_GetTables_Handler,
		},
		{
			MethodName: "GetBackups",
			Handler:    _Minion_GetBackups_Handler,
		},
		{
			MethodName: "ScheduleBackup",
			Handler:    _Minion_ScheduleBackup_Handler,
		},
		{
			MethodName: "UnscheduleBackup",
			Handler:    _Minion_UnscheduleBackup_Handler,
		},
		{
			MethodName: "StartBackup",
			Handler:    _Minion_StartBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minion.proto",
}
