// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package master

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MinionInfo struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	LocalTime            string   `protobuf:"bytes,2,opt,name=localTime,proto3" json:"localTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinionInfo) Reset()         { *m = MinionInfo{} }
func (m *MinionInfo) String() string { return proto.CompactTextString(m) }
func (*MinionInfo) ProtoMessage()    {}
func (*MinionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *MinionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinionInfo.Unmarshal(m, b)
}
func (m *MinionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinionInfo.Marshal(b, m, deterministic)
}
func (m *MinionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinionInfo.Merge(m, src)
}
func (m *MinionInfo) XXX_Size() int {
	return xxx_messageInfo_MinionInfo.Size(m)
}
func (m *MinionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MinionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MinionInfo proto.InternalMessageInfo

func (m *MinionInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *MinionInfo) GetLocalTime() string {
	if m != nil {
		return m.LocalTime
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Query struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

type ListMinions struct {
	Host                 []string `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	Time                 []string `protobuf:"bytes,2,rep,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMinions) Reset()         { *m = ListMinions{} }
func (m *ListMinions) String() string { return proto.CompactTextString(m) }
func (*ListMinions) ProtoMessage()    {}
func (*ListMinions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *ListMinions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMinions.Unmarshal(m, b)
}
func (m *ListMinions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMinions.Marshal(b, m, deterministic)
}
func (m *ListMinions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMinions.Merge(m, src)
}
func (m *ListMinions) XXX_Size() int {
	return xxx_messageInfo_ListMinions.Size(m)
}
func (m *ListMinions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMinions.DiscardUnknown(m)
}

var xxx_messageInfo_ListMinions proto.InternalMessageInfo

func (m *ListMinions) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *ListMinions) GetTime() []string {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*MinionInfo)(nil), "master.MinionInfo")
	proto.RegisterType((*Response)(nil), "master.Response")
	proto.RegisterType((*Query)(nil), "master.Query")
	proto.RegisterType((*ListMinions)(nil), "master.ListMinions")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0x77, 0xdd, 0x15, 0x65, 0x74, 0x13, 0x32, 0x5e, 0x08, 0xe1, 0x60, 0x7a, 0xf2, 0xc4,
	0x41, 0xc2, 0xd5, 0xc4, 0x93, 0x9a, 0xc8, 0x41, 0xe2, 0x0b, 0x14, 0x33, 0x6a, 0x93, 0xd2, 0x92,
	0x76, 0x3c, 0xf8, 0xf6, 0x86, 0x42, 0x85, 0xdb, 0x3f, 0x7f, 0xdb, 0x7c, 0x5f, 0x07, 0xae, 0x07,
	0xe9, 0x99, 0x5c, 0x35, 0x3a, 0xcb, 0x16, 0x93, 0x79, 0x12, 0x0f, 0x00, 0xad, 0x32, 0xca, 0x9a,
	0x17, 0xf3, 0x69, 0x11, 0xe1, 0xf8, 0x6d, 0x3d, 0xe7, 0xfb, 0xdb, 0xfd, 0x5d, 0xda, 0x85, 0x8c,
	0x25, 0xa4, 0xda, 0x7e, 0x48, 0xfd, 0xae, 0x06, 0xca, 0xcf, 0xc2, 0xc1, 0x5a, 0x88, 0x12, 0x2e,
	0x3b, 0xf2, 0xa3, 0x35, 0x9e, 0x30, 0x83, 0xc3, 0xe0, 0xbf, 0x96, 0xc7, 0x53, 0x14, 0x17, 0x70,
	0xfe, 0xf6, 0x43, 0xee, 0x57, 0x34, 0x70, 0xf5, 0xaa, 0x3c, 0xcf, 0x28, 0xbf, 0xe1, 0x1c, 0xfe,
	0x39, 0x08, 0x47, 0x9e, 0x11, 0xa1, 0x9b, 0xf2, 0x3d, 0x43, 0xd2, 0x06, 0x4f, 0xac, 0x21, 0x7d,
	0x26, 0xe9, 0xb8, 0x27, 0xc9, 0x88, 0xd5, 0xf2, 0x97, 0x55, 0xbd, 0xc8, 0x62, 0x17, 0x75, 0xc4,
	0x0e, 0x1b, 0x38, 0x3d, 0x11, 0x3f, 0x6a, 0x1d, 0xb9, 0xa7, 0x78, 0x29, 0x58, 0x15, 0x37, 0x71,
	0xdc, 0xb8, 0x89, 0x5d, 0x9f, 0x84, 0x15, 0xd5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x8e,
	0x3c, 0xa1, 0x32, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	Heartbeat(ctx context.Context, in *MinionInfo, opts ...grpc.CallOption) (*Response, error)
	GetAllMinions(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListMinions, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Heartbeat(ctx context.Context, in *MinionInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) GetAllMinions(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListMinions, error) {
	out := new(ListMinions)
	err := c.cc.Invoke(ctx, "/master.Master/GetAllMinions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	Heartbeat(context.Context, *MinionInfo) (*Response, error)
	GetAllMinions(context.Context, *Query) (*ListMinions, error)
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Heartbeat(ctx, req.(*MinionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_GetAllMinions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetAllMinions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/GetAllMinions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetAllMinions(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "master.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _Master_Heartbeat_Handler,
		},
		{
			MethodName: "GetAllMinions",
			Handler:    _Master_GetAllMinions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
