// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Admin.proto

// This file contains protocol buffers that are used for Admin service.

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRegionInfoResponse_CompactionState int32

const (
	GetRegionInfoResponse_NONE            GetRegionInfoResponse_CompactionState = 0
	GetRegionInfoResponse_MINOR           GetRegionInfoResponse_CompactionState = 1
	GetRegionInfoResponse_MAJOR           GetRegionInfoResponse_CompactionState = 2
	GetRegionInfoResponse_MAJOR_AND_MINOR GetRegionInfoResponse_CompactionState = 3
)

var GetRegionInfoResponse_CompactionState_name = map[int32]string{
	0: "NONE",
	1: "MINOR",
	2: "MAJOR",
	3: "MAJOR_AND_MINOR",
}

var GetRegionInfoResponse_CompactionState_value = map[string]int32{
	"NONE":            0,
	"MINOR":           1,
	"MAJOR":           2,
	"MAJOR_AND_MINOR": 3,
}

func (x GetRegionInfoResponse_CompactionState) Enum() *GetRegionInfoResponse_CompactionState {
	p := new(GetRegionInfoResponse_CompactionState)
	*p = x
	return p
}

func (x GetRegionInfoResponse_CompactionState) String() string {
	return proto.EnumName(GetRegionInfoResponse_CompactionState_name, int32(x))
}

func (x *GetRegionInfoResponse_CompactionState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetRegionInfoResponse_CompactionState_value, data, "GetRegionInfoResponse_CompactionState")
	if err != nil {
		return err
	}
	*x = GetRegionInfoResponse_CompactionState(value)
	return nil
}

func (GetRegionInfoResponse_CompactionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{1, 0}
}

type OpenRegionResponse_RegionOpeningState int32

const (
	OpenRegionResponse_OPENED         OpenRegionResponse_RegionOpeningState = 0
	OpenRegionResponse_ALREADY_OPENED OpenRegionResponse_RegionOpeningState = 1
	OpenRegionResponse_FAILED_OPENING OpenRegionResponse_RegionOpeningState = 2
)

var OpenRegionResponse_RegionOpeningState_name = map[int32]string{
	0: "OPENED",
	1: "ALREADY_OPENED",
	2: "FAILED_OPENING",
}

var OpenRegionResponse_RegionOpeningState_value = map[string]int32{
	"OPENED":         0,
	"ALREADY_OPENED": 1,
	"FAILED_OPENING": 2,
}

func (x OpenRegionResponse_RegionOpeningState) Enum() *OpenRegionResponse_RegionOpeningState {
	p := new(OpenRegionResponse_RegionOpeningState)
	*p = x
	return p
}

func (x OpenRegionResponse_RegionOpeningState) String() string {
	return proto.EnumName(OpenRegionResponse_RegionOpeningState_name, int32(x))
}

func (x *OpenRegionResponse_RegionOpeningState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OpenRegionResponse_RegionOpeningState_value, data, "OpenRegionResponse_RegionOpeningState")
	if err != nil {
		return err
	}
	*x = OpenRegionResponse_RegionOpeningState(value)
	return nil
}

func (OpenRegionResponse_RegionOpeningState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{7, 0}
}

type GetRegionInfoRequest struct {
	Region               *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	CompactionState      *bool            `protobuf:"varint,2,opt,name=compaction_state,json=compactionState" json:"compaction_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetRegionInfoRequest) Reset()         { *m = GetRegionInfoRequest{} }
func (m *GetRegionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetRegionInfoRequest) ProtoMessage()    {}
func (*GetRegionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{0}
}

func (m *GetRegionInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRegionInfoRequest.Unmarshal(m, b)
}
func (m *GetRegionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRegionInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetRegionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRegionInfoRequest.Merge(m, src)
}
func (m *GetRegionInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetRegionInfoRequest.Size(m)
}
func (m *GetRegionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRegionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRegionInfoRequest proto.InternalMessageInfo

func (m *GetRegionInfoRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *GetRegionInfoRequest) GetCompactionState() bool {
	if m != nil && m.CompactionState != nil {
		return *m.CompactionState
	}
	return false
}

type GetRegionInfoResponse struct {
	RegionInfo           *RegionInfo                            `protobuf:"bytes,1,req,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	CompactionState      *GetRegionInfoResponse_CompactionState `protobuf:"varint,2,opt,name=compaction_state,json=compactionState,enum=pb.GetRegionInfoResponse_CompactionState" json:"compaction_state,omitempty"`
	IsRecovering         *bool                                  `protobuf:"varint,3,opt,name=isRecovering" json:"isRecovering,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetRegionInfoResponse) Reset()         { *m = GetRegionInfoResponse{} }
func (m *GetRegionInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetRegionInfoResponse) ProtoMessage()    {}
func (*GetRegionInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{1}
}

func (m *GetRegionInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRegionInfoResponse.Unmarshal(m, b)
}
func (m *GetRegionInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRegionInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetRegionInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRegionInfoResponse.Merge(m, src)
}
func (m *GetRegionInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetRegionInfoResponse.Size(m)
}
func (m *GetRegionInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRegionInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRegionInfoResponse proto.InternalMessageInfo

func (m *GetRegionInfoResponse) GetRegionInfo() *RegionInfo {
	if m != nil {
		return m.RegionInfo
	}
	return nil
}

func (m *GetRegionInfoResponse) GetCompactionState() GetRegionInfoResponse_CompactionState {
	if m != nil && m.CompactionState != nil {
		return *m.CompactionState
	}
	return GetRegionInfoResponse_NONE
}

func (m *GetRegionInfoResponse) GetIsRecovering() bool {
	if m != nil && m.IsRecovering != nil {
		return *m.IsRecovering
	}
	return false
}

//*
// Get a list of store files for a set of column families in a particular region.
// If no column family is specified, get the store files for all column families.
type GetStoreFileRequest struct {
	Region               *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	Family               [][]byte         `protobuf:"bytes,2,rep,name=family" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetStoreFileRequest) Reset()         { *m = GetStoreFileRequest{} }
func (m *GetStoreFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetStoreFileRequest) ProtoMessage()    {}
func (*GetStoreFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{2}
}

func (m *GetStoreFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoreFileRequest.Unmarshal(m, b)
}
func (m *GetStoreFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoreFileRequest.Marshal(b, m, deterministic)
}
func (m *GetStoreFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoreFileRequest.Merge(m, src)
}
func (m *GetStoreFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetStoreFileRequest.Size(m)
}
func (m *GetStoreFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoreFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoreFileRequest proto.InternalMessageInfo

func (m *GetStoreFileRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *GetStoreFileRequest) GetFamily() [][]byte {
	if m != nil {
		return m.Family
	}
	return nil
}

type GetStoreFileResponse struct {
	StoreFile            []string `protobuf:"bytes,1,rep,name=store_file,json=storeFile" json:"store_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStoreFileResponse) Reset()         { *m = GetStoreFileResponse{} }
func (m *GetStoreFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetStoreFileResponse) ProtoMessage()    {}
func (*GetStoreFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{3}
}

func (m *GetStoreFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoreFileResponse.Unmarshal(m, b)
}
func (m *GetStoreFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoreFileResponse.Marshal(b, m, deterministic)
}
func (m *GetStoreFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoreFileResponse.Merge(m, src)
}
func (m *GetStoreFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetStoreFileResponse.Size(m)
}
func (m *GetStoreFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoreFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoreFileResponse proto.InternalMessageInfo

func (m *GetStoreFileResponse) GetStoreFile() []string {
	if m != nil {
		return m.StoreFile
	}
	return nil
}

type GetOnlineRegionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOnlineRegionRequest) Reset()         { *m = GetOnlineRegionRequest{} }
func (m *GetOnlineRegionRequest) String() string { return proto.CompactTextString(m) }
func (*GetOnlineRegionRequest) ProtoMessage()    {}
func (*GetOnlineRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{4}
}

func (m *GetOnlineRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineRegionRequest.Unmarshal(m, b)
}
func (m *GetOnlineRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineRegionRequest.Marshal(b, m, deterministic)
}
func (m *GetOnlineRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineRegionRequest.Merge(m, src)
}
func (m *GetOnlineRegionRequest) XXX_Size() int {
	return xxx_messageInfo_GetOnlineRegionRequest.Size(m)
}
func (m *GetOnlineRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineRegionRequest proto.InternalMessageInfo

type GetOnlineRegionResponse struct {
	RegionInfo           []*RegionInfo `protobuf:"bytes,1,rep,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetOnlineRegionResponse) Reset()         { *m = GetOnlineRegionResponse{} }
func (m *GetOnlineRegionResponse) String() string { return proto.CompactTextString(m) }
func (*GetOnlineRegionResponse) ProtoMessage()    {}
func (*GetOnlineRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{5}
}

func (m *GetOnlineRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineRegionResponse.Unmarshal(m, b)
}
func (m *GetOnlineRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineRegionResponse.Marshal(b, m, deterministic)
}
func (m *GetOnlineRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineRegionResponse.Merge(m, src)
}
func (m *GetOnlineRegionResponse) XXX_Size() int {
	return xxx_messageInfo_GetOnlineRegionResponse.Size(m)
}
func (m *GetOnlineRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineRegionResponse proto.InternalMessageInfo

func (m *GetOnlineRegionResponse) GetRegionInfo() []*RegionInfo {
	if m != nil {
		return m.RegionInfo
	}
	return nil
}

type OpenRegionRequest struct {
	OpenInfo []*OpenRegionRequest_RegionOpenInfo `protobuf:"bytes,1,rep,name=open_info,json=openInfo" json:"open_info,omitempty"`
	// the intended server for this RPC.
	ServerStartCode *uint64 `protobuf:"varint,2,opt,name=serverStartCode" json:"serverStartCode,omitempty"`
	// wall clock time from master
	MasterSystemTime     *uint64  `protobuf:"varint,5,opt,name=master_system_time,json=masterSystemTime" json:"master_system_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRegionRequest) Reset()         { *m = OpenRegionRequest{} }
func (m *OpenRegionRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRegionRequest) ProtoMessage()    {}
func (*OpenRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{6}
}

func (m *OpenRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRegionRequest.Unmarshal(m, b)
}
func (m *OpenRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRegionRequest.Marshal(b, m, deterministic)
}
func (m *OpenRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRegionRequest.Merge(m, src)
}
func (m *OpenRegionRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRegionRequest.Size(m)
}
func (m *OpenRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRegionRequest proto.InternalMessageInfo

func (m *OpenRegionRequest) GetOpenInfo() []*OpenRegionRequest_RegionOpenInfo {
	if m != nil {
		return m.OpenInfo
	}
	return nil
}

func (m *OpenRegionRequest) GetServerStartCode() uint64 {
	if m != nil && m.ServerStartCode != nil {
		return *m.ServerStartCode
	}
	return 0
}

func (m *OpenRegionRequest) GetMasterSystemTime() uint64 {
	if m != nil && m.MasterSystemTime != nil {
		return *m.MasterSystemTime
	}
	return 0
}

type OpenRegionRequest_RegionOpenInfo struct {
	Region               *RegionInfo   `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	VersionOfOfflineNode *uint32       `protobuf:"varint,2,opt,name=version_of_offline_node,json=versionOfOfflineNode" json:"version_of_offline_node,omitempty"`
	FavoredNodes         []*ServerName `protobuf:"bytes,3,rep,name=favored_nodes,json=favoredNodes" json:"favored_nodes,omitempty"`
	// open region for distributedLogReplay
	OpenForDistributedLogReplay *bool    `protobuf:"varint,4,opt,name=openForDistributedLogReplay" json:"openForDistributedLogReplay,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *OpenRegionRequest_RegionOpenInfo) Reset()         { *m = OpenRegionRequest_RegionOpenInfo{} }
func (m *OpenRegionRequest_RegionOpenInfo) String() string { return proto.CompactTextString(m) }
func (*OpenRegionRequest_RegionOpenInfo) ProtoMessage()    {}
func (*OpenRegionRequest_RegionOpenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{6, 0}
}

func (m *OpenRegionRequest_RegionOpenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRegionRequest_RegionOpenInfo.Unmarshal(m, b)
}
func (m *OpenRegionRequest_RegionOpenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRegionRequest_RegionOpenInfo.Marshal(b, m, deterministic)
}
func (m *OpenRegionRequest_RegionOpenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRegionRequest_RegionOpenInfo.Merge(m, src)
}
func (m *OpenRegionRequest_RegionOpenInfo) XXX_Size() int {
	return xxx_messageInfo_OpenRegionRequest_RegionOpenInfo.Size(m)
}
func (m *OpenRegionRequest_RegionOpenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRegionRequest_RegionOpenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRegionRequest_RegionOpenInfo proto.InternalMessageInfo

func (m *OpenRegionRequest_RegionOpenInfo) GetRegion() *RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *OpenRegionRequest_RegionOpenInfo) GetVersionOfOfflineNode() uint32 {
	if m != nil && m.VersionOfOfflineNode != nil {
		return *m.VersionOfOfflineNode
	}
	return 0
}

func (m *OpenRegionRequest_RegionOpenInfo) GetFavoredNodes() []*ServerName {
	if m != nil {
		return m.FavoredNodes
	}
	return nil
}

func (m *OpenRegionRequest_RegionOpenInfo) GetOpenForDistributedLogReplay() bool {
	if m != nil && m.OpenForDistributedLogReplay != nil {
		return *m.OpenForDistributedLogReplay
	}
	return false
}

type OpenRegionResponse struct {
	OpeningState         []OpenRegionResponse_RegionOpeningState `protobuf:"varint,1,rep,name=opening_state,json=openingState,enum=pb.OpenRegionResponse_RegionOpeningState" json:"opening_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *OpenRegionResponse) Reset()         { *m = OpenRegionResponse{} }
func (m *OpenRegionResponse) String() string { return proto.CompactTextString(m) }
func (*OpenRegionResponse) ProtoMessage()    {}
func (*OpenRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{7}
}

func (m *OpenRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRegionResponse.Unmarshal(m, b)
}
func (m *OpenRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRegionResponse.Marshal(b, m, deterministic)
}
func (m *OpenRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRegionResponse.Merge(m, src)
}
func (m *OpenRegionResponse) XXX_Size() int {
	return xxx_messageInfo_OpenRegionResponse.Size(m)
}
func (m *OpenRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRegionResponse proto.InternalMessageInfo

func (m *OpenRegionResponse) GetOpeningState() []OpenRegionResponse_RegionOpeningState {
	if m != nil {
		return m.OpeningState
	}
	return nil
}

type WarmupRegionRequest struct {
	RegionInfo           *RegionInfo `protobuf:"bytes,1,req,name=regionInfo" json:"regionInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WarmupRegionRequest) Reset()         { *m = WarmupRegionRequest{} }
func (m *WarmupRegionRequest) String() string { return proto.CompactTextString(m) }
func (*WarmupRegionRequest) ProtoMessage()    {}
func (*WarmupRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{8}
}

func (m *WarmupRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarmupRegionRequest.Unmarshal(m, b)
}
func (m *WarmupRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarmupRegionRequest.Marshal(b, m, deterministic)
}
func (m *WarmupRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarmupRegionRequest.Merge(m, src)
}
func (m *WarmupRegionRequest) XXX_Size() int {
	return xxx_messageInfo_WarmupRegionRequest.Size(m)
}
func (m *WarmupRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WarmupRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WarmupRegionRequest proto.InternalMessageInfo

func (m *WarmupRegionRequest) GetRegionInfo() *RegionInfo {
	if m != nil {
		return m.RegionInfo
	}
	return nil
}

type WarmupRegionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WarmupRegionResponse) Reset()         { *m = WarmupRegionResponse{} }
func (m *WarmupRegionResponse) String() string { return proto.CompactTextString(m) }
func (*WarmupRegionResponse) ProtoMessage()    {}
func (*WarmupRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{9}
}

func (m *WarmupRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarmupRegionResponse.Unmarshal(m, b)
}
func (m *WarmupRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarmupRegionResponse.Marshal(b, m, deterministic)
}
func (m *WarmupRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarmupRegionResponse.Merge(m, src)
}
func (m *WarmupRegionResponse) XXX_Size() int {
	return xxx_messageInfo_WarmupRegionResponse.Size(m)
}
func (m *WarmupRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WarmupRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WarmupRegionResponse proto.InternalMessageInfo

//*
// Closes the specified region and will use or not use ZK during the close
// according to the specified flag.
type CloseRegionRequest struct {
	Region               *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	VersionOfClosingNode *uint32          `protobuf:"varint,2,opt,name=version_of_closing_node,json=versionOfClosingNode" json:"version_of_closing_node,omitempty"`
	TransitionIn_ZK      *bool            `protobuf:"varint,3,opt,name=transition_in_ZK,json=transitionInZK,def=1" json:"transition_in_ZK,omitempty"`
	DestinationServer    *ServerName      `protobuf:"bytes,4,opt,name=destination_server,json=destinationServer" json:"destination_server,omitempty"`
	// the intended server for this RPC.
	ServerStartCode      *uint64  `protobuf:"varint,5,opt,name=serverStartCode" json:"serverStartCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRegionRequest) Reset()         { *m = CloseRegionRequest{} }
func (m *CloseRegionRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRegionRequest) ProtoMessage()    {}
func (*CloseRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{10}
}

func (m *CloseRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRegionRequest.Unmarshal(m, b)
}
func (m *CloseRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRegionRequest.Marshal(b, m, deterministic)
}
func (m *CloseRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRegionRequest.Merge(m, src)
}
func (m *CloseRegionRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRegionRequest.Size(m)
}
func (m *CloseRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRegionRequest proto.InternalMessageInfo

const Default_CloseRegionRequest_TransitionIn_ZK bool = true

func (m *CloseRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *CloseRegionRequest) GetVersionOfClosingNode() uint32 {
	if m != nil && m.VersionOfClosingNode != nil {
		return *m.VersionOfClosingNode
	}
	return 0
}

func (m *CloseRegionRequest) GetTransitionIn_ZK() bool {
	if m != nil && m.TransitionIn_ZK != nil {
		return *m.TransitionIn_ZK
	}
	return Default_CloseRegionRequest_TransitionIn_ZK
}

func (m *CloseRegionRequest) GetDestinationServer() *ServerName {
	if m != nil {
		return m.DestinationServer
	}
	return nil
}

func (m *CloseRegionRequest) GetServerStartCode() uint64 {
	if m != nil && m.ServerStartCode != nil {
		return *m.ServerStartCode
	}
	return 0
}

type CloseRegionResponse struct {
	Closed               *bool    `protobuf:"varint,1,req,name=closed" json:"closed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRegionResponse) Reset()         { *m = CloseRegionResponse{} }
func (m *CloseRegionResponse) String() string { return proto.CompactTextString(m) }
func (*CloseRegionResponse) ProtoMessage()    {}
func (*CloseRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{11}
}

func (m *CloseRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRegionResponse.Unmarshal(m, b)
}
func (m *CloseRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRegionResponse.Marshal(b, m, deterministic)
}
func (m *CloseRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRegionResponse.Merge(m, src)
}
func (m *CloseRegionResponse) XXX_Size() int {
	return xxx_messageInfo_CloseRegionResponse.Size(m)
}
func (m *CloseRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRegionResponse proto.InternalMessageInfo

func (m *CloseRegionResponse) GetClosed() bool {
	if m != nil && m.Closed != nil {
		return *m.Closed
	}
	return false
}

//*
// Flushes the MemStore of the specified region.
// <p>
// This method is synchronous.
type FlushRegionRequest struct {
	Region               *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	IfOlderThanTs        *uint64          `protobuf:"varint,2,opt,name=if_older_than_ts,json=ifOlderThanTs" json:"if_older_than_ts,omitempty"`
	WriteFlushWalMarker  *bool            `protobuf:"varint,3,opt,name=write_flush_wal_marker,json=writeFlushWalMarker" json:"write_flush_wal_marker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FlushRegionRequest) Reset()         { *m = FlushRegionRequest{} }
func (m *FlushRegionRequest) String() string { return proto.CompactTextString(m) }
func (*FlushRegionRequest) ProtoMessage()    {}
func (*FlushRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{12}
}

func (m *FlushRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlushRegionRequest.Unmarshal(m, b)
}
func (m *FlushRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlushRegionRequest.Marshal(b, m, deterministic)
}
func (m *FlushRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlushRegionRequest.Merge(m, src)
}
func (m *FlushRegionRequest) XXX_Size() int {
	return xxx_messageInfo_FlushRegionRequest.Size(m)
}
func (m *FlushRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FlushRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FlushRegionRequest proto.InternalMessageInfo

func (m *FlushRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *FlushRegionRequest) GetIfOlderThanTs() uint64 {
	if m != nil && m.IfOlderThanTs != nil {
		return *m.IfOlderThanTs
	}
	return 0
}

func (m *FlushRegionRequest) GetWriteFlushWalMarker() bool {
	if m != nil && m.WriteFlushWalMarker != nil {
		return *m.WriteFlushWalMarker
	}
	return false
}

type FlushRegionResponse struct {
	LastFlushTime        *uint64  `protobuf:"varint,1,req,name=last_flush_time,json=lastFlushTime" json:"last_flush_time,omitempty"`
	Flushed              *bool    `protobuf:"varint,2,opt,name=flushed" json:"flushed,omitempty"`
	WroteFlushWalMarker  *bool    `protobuf:"varint,3,opt,name=wrote_flush_wal_marker,json=wroteFlushWalMarker" json:"wrote_flush_wal_marker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlushRegionResponse) Reset()         { *m = FlushRegionResponse{} }
func (m *FlushRegionResponse) String() string { return proto.CompactTextString(m) }
func (*FlushRegionResponse) ProtoMessage()    {}
func (*FlushRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{13}
}

func (m *FlushRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlushRegionResponse.Unmarshal(m, b)
}
func (m *FlushRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlushRegionResponse.Marshal(b, m, deterministic)
}
func (m *FlushRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlushRegionResponse.Merge(m, src)
}
func (m *FlushRegionResponse) XXX_Size() int {
	return xxx_messageInfo_FlushRegionResponse.Size(m)
}
func (m *FlushRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlushRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlushRegionResponse proto.InternalMessageInfo

func (m *FlushRegionResponse) GetLastFlushTime() uint64 {
	if m != nil && m.LastFlushTime != nil {
		return *m.LastFlushTime
	}
	return 0
}

func (m *FlushRegionResponse) GetFlushed() bool {
	if m != nil && m.Flushed != nil {
		return *m.Flushed
	}
	return false
}

func (m *FlushRegionResponse) GetWroteFlushWalMarker() bool {
	if m != nil && m.WroteFlushWalMarker != nil {
		return *m.WroteFlushWalMarker
	}
	return false
}

//*
// Splits the specified region.
// <p>
// This method currently flushes the region and then forces a compaction which
// will then trigger a split.  The flush is done synchronously but the
// compaction is asynchronous.
type SplitRegionRequest struct {
	Region               *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	SplitPoint           []byte           `protobuf:"bytes,2,opt,name=split_point,json=splitPoint" json:"split_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SplitRegionRequest) Reset()         { *m = SplitRegionRequest{} }
func (m *SplitRegionRequest) String() string { return proto.CompactTextString(m) }
func (*SplitRegionRequest) ProtoMessage()    {}
func (*SplitRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{14}
}

func (m *SplitRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitRegionRequest.Unmarshal(m, b)
}
func (m *SplitRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitRegionRequest.Marshal(b, m, deterministic)
}
func (m *SplitRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitRegionRequest.Merge(m, src)
}
func (m *SplitRegionRequest) XXX_Size() int {
	return xxx_messageInfo_SplitRegionRequest.Size(m)
}
func (m *SplitRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SplitRegionRequest proto.InternalMessageInfo

func (m *SplitRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *SplitRegionRequest) GetSplitPoint() []byte {
	if m != nil {
		return m.SplitPoint
	}
	return nil
}

type SplitRegionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitRegionResponse) Reset()         { *m = SplitRegionResponse{} }
func (m *SplitRegionResponse) String() string { return proto.CompactTextString(m) }
func (*SplitRegionResponse) ProtoMessage()    {}
func (*SplitRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{15}
}

func (m *SplitRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitRegionResponse.Unmarshal(m, b)
}
func (m *SplitRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitRegionResponse.Marshal(b, m, deterministic)
}
func (m *SplitRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitRegionResponse.Merge(m, src)
}
func (m *SplitRegionResponse) XXX_Size() int {
	return xxx_messageInfo_SplitRegionResponse.Size(m)
}
func (m *SplitRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SplitRegionResponse proto.InternalMessageInfo

//*
// Compacts the specified region.  Performs a major compaction if specified.
// <p>
// This method is asynchronous.
type CompactRegionRequest struct {
	Region               *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	Major                *bool            `protobuf:"varint,2,opt,name=major" json:"major,omitempty"`
	Family               []byte           `protobuf:"bytes,3,opt,name=family" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CompactRegionRequest) Reset()         { *m = CompactRegionRequest{} }
func (m *CompactRegionRequest) String() string { return proto.CompactTextString(m) }
func (*CompactRegionRequest) ProtoMessage()    {}
func (*CompactRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{16}
}

func (m *CompactRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactRegionRequest.Unmarshal(m, b)
}
func (m *CompactRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactRegionRequest.Marshal(b, m, deterministic)
}
func (m *CompactRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactRegionRequest.Merge(m, src)
}
func (m *CompactRegionRequest) XXX_Size() int {
	return xxx_messageInfo_CompactRegionRequest.Size(m)
}
func (m *CompactRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompactRegionRequest proto.InternalMessageInfo

func (m *CompactRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *CompactRegionRequest) GetMajor() bool {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return false
}

func (m *CompactRegionRequest) GetFamily() []byte {
	if m != nil {
		return m.Family
	}
	return nil
}

type CompactRegionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompactRegionResponse) Reset()         { *m = CompactRegionResponse{} }
func (m *CompactRegionResponse) String() string { return proto.CompactTextString(m) }
func (*CompactRegionResponse) ProtoMessage()    {}
func (*CompactRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{17}
}

func (m *CompactRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactRegionResponse.Unmarshal(m, b)
}
func (m *CompactRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactRegionResponse.Marshal(b, m, deterministic)
}
func (m *CompactRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactRegionResponse.Merge(m, src)
}
func (m *CompactRegionResponse) XXX_Size() int {
	return xxx_messageInfo_CompactRegionResponse.Size(m)
}
func (m *CompactRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompactRegionResponse proto.InternalMessageInfo

type UpdateFavoredNodesRequest struct {
	UpdateInfo           []*UpdateFavoredNodesRequest_RegionUpdateInfo `protobuf:"bytes,1,rep,name=update_info,json=updateInfo" json:"update_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *UpdateFavoredNodesRequest) Reset()         { *m = UpdateFavoredNodesRequest{} }
func (m *UpdateFavoredNodesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFavoredNodesRequest) ProtoMessage()    {}
func (*UpdateFavoredNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{18}
}

func (m *UpdateFavoredNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFavoredNodesRequest.Unmarshal(m, b)
}
func (m *UpdateFavoredNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFavoredNodesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFavoredNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFavoredNodesRequest.Merge(m, src)
}
func (m *UpdateFavoredNodesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFavoredNodesRequest.Size(m)
}
func (m *UpdateFavoredNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFavoredNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFavoredNodesRequest proto.InternalMessageInfo

func (m *UpdateFavoredNodesRequest) GetUpdateInfo() []*UpdateFavoredNodesRequest_RegionUpdateInfo {
	if m != nil {
		return m.UpdateInfo
	}
	return nil
}

type UpdateFavoredNodesRequest_RegionUpdateInfo struct {
	Region               *RegionInfo   `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	FavoredNodes         []*ServerName `protobuf:"bytes,2,rep,name=favored_nodes,json=favoredNodes" json:"favored_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) Reset() {
	*m = UpdateFavoredNodesRequest_RegionUpdateInfo{}
}
func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateFavoredNodesRequest_RegionUpdateInfo) ProtoMessage() {}
func (*UpdateFavoredNodesRequest_RegionUpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{18, 0}
}

func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFavoredNodesRequest_RegionUpdateInfo.Unmarshal(m, b)
}
func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFavoredNodesRequest_RegionUpdateInfo.Marshal(b, m, deterministic)
}
func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFavoredNodesRequest_RegionUpdateInfo.Merge(m, src)
}
func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateFavoredNodesRequest_RegionUpdateInfo.Size(m)
}
func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFavoredNodesRequest_RegionUpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFavoredNodesRequest_RegionUpdateInfo proto.InternalMessageInfo

func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) GetRegion() *RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *UpdateFavoredNodesRequest_RegionUpdateInfo) GetFavoredNodes() []*ServerName {
	if m != nil {
		return m.FavoredNodes
	}
	return nil
}

type UpdateFavoredNodesResponse struct {
	Response             *uint32  `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFavoredNodesResponse) Reset()         { *m = UpdateFavoredNodesResponse{} }
func (m *UpdateFavoredNodesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFavoredNodesResponse) ProtoMessage()    {}
func (*UpdateFavoredNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{19}
}

func (m *UpdateFavoredNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFavoredNodesResponse.Unmarshal(m, b)
}
func (m *UpdateFavoredNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFavoredNodesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFavoredNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFavoredNodesResponse.Merge(m, src)
}
func (m *UpdateFavoredNodesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFavoredNodesResponse.Size(m)
}
func (m *UpdateFavoredNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFavoredNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFavoredNodesResponse proto.InternalMessageInfo

func (m *UpdateFavoredNodesResponse) GetResponse() uint32 {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return 0
}

//*
// Merges the specified regions.
// <p>
// This method currently closes the regions and then merges them
type MergeRegionsRequest struct {
	RegionA  *RegionSpecifier `protobuf:"bytes,1,req,name=region_a,json=regionA" json:"region_a,omitempty"`
	RegionB  *RegionSpecifier `protobuf:"bytes,2,req,name=region_b,json=regionB" json:"region_b,omitempty"`
	Forcible *bool            `protobuf:"varint,3,opt,name=forcible,def=0" json:"forcible,omitempty"`
	// wall clock time from master
	MasterSystemTime     *uint64  `protobuf:"varint,4,opt,name=master_system_time,json=masterSystemTime" json:"master_system_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeRegionsRequest) Reset()         { *m = MergeRegionsRequest{} }
func (m *MergeRegionsRequest) String() string { return proto.CompactTextString(m) }
func (*MergeRegionsRequest) ProtoMessage()    {}
func (*MergeRegionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{20}
}

func (m *MergeRegionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeRegionsRequest.Unmarshal(m, b)
}
func (m *MergeRegionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeRegionsRequest.Marshal(b, m, deterministic)
}
func (m *MergeRegionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeRegionsRequest.Merge(m, src)
}
func (m *MergeRegionsRequest) XXX_Size() int {
	return xxx_messageInfo_MergeRegionsRequest.Size(m)
}
func (m *MergeRegionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeRegionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MergeRegionsRequest proto.InternalMessageInfo

const Default_MergeRegionsRequest_Forcible bool = false

func (m *MergeRegionsRequest) GetRegionA() *RegionSpecifier {
	if m != nil {
		return m.RegionA
	}
	return nil
}

func (m *MergeRegionsRequest) GetRegionB() *RegionSpecifier {
	if m != nil {
		return m.RegionB
	}
	return nil
}

func (m *MergeRegionsRequest) GetForcible() bool {
	if m != nil && m.Forcible != nil {
		return *m.Forcible
	}
	return Default_MergeRegionsRequest_Forcible
}

func (m *MergeRegionsRequest) GetMasterSystemTime() uint64 {
	if m != nil && m.MasterSystemTime != nil {
		return *m.MasterSystemTime
	}
	return 0
}

type MergeRegionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeRegionsResponse) Reset()         { *m = MergeRegionsResponse{} }
func (m *MergeRegionsResponse) String() string { return proto.CompactTextString(m) }
func (*MergeRegionsResponse) ProtoMessage()    {}
func (*MergeRegionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{21}
}

func (m *MergeRegionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeRegionsResponse.Unmarshal(m, b)
}
func (m *MergeRegionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeRegionsResponse.Marshal(b, m, deterministic)
}
func (m *MergeRegionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeRegionsResponse.Merge(m, src)
}
func (m *MergeRegionsResponse) XXX_Size() int {
	return xxx_messageInfo_MergeRegionsResponse.Size(m)
}
func (m *MergeRegionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeRegionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MergeRegionsResponse proto.InternalMessageInfo

// Protocol buffer version of WAL for replication
type WALEntry struct {
	Key *WALKey `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	// Following may be null if the KVs/Cells are carried along the side in a cellblock (See
	// RPC for more on cellblocks). If Cells/KVs are in a cellblock, this next field is null
	// and associated_cell_count has count of Cells associated w/ this WALEntry
	KeyValueBytes [][]byte `protobuf:"bytes,2,rep,name=key_value_bytes,json=keyValueBytes" json:"key_value_bytes,omitempty"`
	// If Cell data is carried alongside in a cellblock, this is count of Cells in the cellblock.
	AssociatedCellCount  *int32   `protobuf:"varint,3,opt,name=associated_cell_count,json=associatedCellCount" json:"associated_cell_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WALEntry) Reset()         { *m = WALEntry{} }
func (m *WALEntry) String() string { return proto.CompactTextString(m) }
func (*WALEntry) ProtoMessage()    {}
func (*WALEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{22}
}

func (m *WALEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WALEntry.Unmarshal(m, b)
}
func (m *WALEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WALEntry.Marshal(b, m, deterministic)
}
func (m *WALEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WALEntry.Merge(m, src)
}
func (m *WALEntry) XXX_Size() int {
	return xxx_messageInfo_WALEntry.Size(m)
}
func (m *WALEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_WALEntry.DiscardUnknown(m)
}

var xxx_messageInfo_WALEntry proto.InternalMessageInfo

func (m *WALEntry) GetKey() *WALKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *WALEntry) GetKeyValueBytes() [][]byte {
	if m != nil {
		return m.KeyValueBytes
	}
	return nil
}

func (m *WALEntry) GetAssociatedCellCount() int32 {
	if m != nil && m.AssociatedCellCount != nil {
		return *m.AssociatedCellCount
	}
	return 0
}

//*
// Replicates the given entries. The guarantee is that the given entries
// will be durable on the slave cluster if this method returns without
// any exception.  hbase.replication has to be set to true for this to work.
type ReplicateWALEntryRequest struct {
	Entry                      []*WALEntry `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
	ReplicationClusterId       *string     `protobuf:"bytes,2,opt,name=replicationClusterId" json:"replicationClusterId,omitempty"`
	SourceBaseNamespaceDirPath *string     `protobuf:"bytes,3,opt,name=sourceBaseNamespaceDirPath" json:"sourceBaseNamespaceDirPath,omitempty"`
	SourceHFileArchiveDirPath  *string     `protobuf:"bytes,4,opt,name=sourceHFileArchiveDirPath" json:"sourceHFileArchiveDirPath,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}    `json:"-"`
	XXX_unrecognized           []byte      `json:"-"`
	XXX_sizecache              int32       `json:"-"`
}

func (m *ReplicateWALEntryRequest) Reset()         { *m = ReplicateWALEntryRequest{} }
func (m *ReplicateWALEntryRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicateWALEntryRequest) ProtoMessage()    {}
func (*ReplicateWALEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{23}
}

func (m *ReplicateWALEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateWALEntryRequest.Unmarshal(m, b)
}
func (m *ReplicateWALEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateWALEntryRequest.Marshal(b, m, deterministic)
}
func (m *ReplicateWALEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateWALEntryRequest.Merge(m, src)
}
func (m *ReplicateWALEntryRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicateWALEntryRequest.Size(m)
}
func (m *ReplicateWALEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateWALEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateWALEntryRequest proto.InternalMessageInfo

func (m *ReplicateWALEntryRequest) GetEntry() []*WALEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *ReplicateWALEntryRequest) GetReplicationClusterId() string {
	if m != nil && m.ReplicationClusterId != nil {
		return *m.ReplicationClusterId
	}
	return ""
}

func (m *ReplicateWALEntryRequest) GetSourceBaseNamespaceDirPath() string {
	if m != nil && m.SourceBaseNamespaceDirPath != nil {
		return *m.SourceBaseNamespaceDirPath
	}
	return ""
}

func (m *ReplicateWALEntryRequest) GetSourceHFileArchiveDirPath() string {
	if m != nil && m.SourceHFileArchiveDirPath != nil {
		return *m.SourceHFileArchiveDirPath
	}
	return ""
}

type ReplicateWALEntryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateWALEntryResponse) Reset()         { *m = ReplicateWALEntryResponse{} }
func (m *ReplicateWALEntryResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicateWALEntryResponse) ProtoMessage()    {}
func (*ReplicateWALEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{24}
}

func (m *ReplicateWALEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateWALEntryResponse.Unmarshal(m, b)
}
func (m *ReplicateWALEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateWALEntryResponse.Marshal(b, m, deterministic)
}
func (m *ReplicateWALEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateWALEntryResponse.Merge(m, src)
}
func (m *ReplicateWALEntryResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicateWALEntryResponse.Size(m)
}
func (m *ReplicateWALEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateWALEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateWALEntryResponse proto.InternalMessageInfo

type RollWALWriterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollWALWriterRequest) Reset()         { *m = RollWALWriterRequest{} }
func (m *RollWALWriterRequest) String() string { return proto.CompactTextString(m) }
func (*RollWALWriterRequest) ProtoMessage()    {}
func (*RollWALWriterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{25}
}

func (m *RollWALWriterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollWALWriterRequest.Unmarshal(m, b)
}
func (m *RollWALWriterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollWALWriterRequest.Marshal(b, m, deterministic)
}
func (m *RollWALWriterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollWALWriterRequest.Merge(m, src)
}
func (m *RollWALWriterRequest) XXX_Size() int {
	return xxx_messageInfo_RollWALWriterRequest.Size(m)
}
func (m *RollWALWriterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollWALWriterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollWALWriterRequest proto.InternalMessageInfo

//
// Roll request responses no longer include regions to flush
// this list will always be empty when talking to a 1.0 server
type RollWALWriterResponse struct {
	// A list of encoded name of regions to flush
	RegionToFlush        [][]byte `protobuf:"bytes,1,rep,name=region_to_flush,json=regionToFlush" json:"region_to_flush,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollWALWriterResponse) Reset()         { *m = RollWALWriterResponse{} }
func (m *RollWALWriterResponse) String() string { return proto.CompactTextString(m) }
func (*RollWALWriterResponse) ProtoMessage()    {}
func (*RollWALWriterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{26}
}

func (m *RollWALWriterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollWALWriterResponse.Unmarshal(m, b)
}
func (m *RollWALWriterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollWALWriterResponse.Marshal(b, m, deterministic)
}
func (m *RollWALWriterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollWALWriterResponse.Merge(m, src)
}
func (m *RollWALWriterResponse) XXX_Size() int {
	return xxx_messageInfo_RollWALWriterResponse.Size(m)
}
func (m *RollWALWriterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollWALWriterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollWALWriterResponse proto.InternalMessageInfo

func (m *RollWALWriterResponse) GetRegionToFlush() [][]byte {
	if m != nil {
		return m.RegionToFlush
	}
	return nil
}

type StopServerRequest struct {
	Reason               *string  `protobuf:"bytes,1,req,name=reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServerRequest) Reset()         { *m = StopServerRequest{} }
func (m *StopServerRequest) String() string { return proto.CompactTextString(m) }
func (*StopServerRequest) ProtoMessage()    {}
func (*StopServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{27}
}

func (m *StopServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServerRequest.Unmarshal(m, b)
}
func (m *StopServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServerRequest.Marshal(b, m, deterministic)
}
func (m *StopServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServerRequest.Merge(m, src)
}
func (m *StopServerRequest) XXX_Size() int {
	return xxx_messageInfo_StopServerRequest.Size(m)
}
func (m *StopServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopServerRequest proto.InternalMessageInfo

func (m *StopServerRequest) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type StopServerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServerResponse) Reset()         { *m = StopServerResponse{} }
func (m *StopServerResponse) String() string { return proto.CompactTextString(m) }
func (*StopServerResponse) ProtoMessage()    {}
func (*StopServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{28}
}

func (m *StopServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServerResponse.Unmarshal(m, b)
}
func (m *StopServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServerResponse.Marshal(b, m, deterministic)
}
func (m *StopServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServerResponse.Merge(m, src)
}
func (m *StopServerResponse) XXX_Size() int {
	return xxx_messageInfo_StopServerResponse.Size(m)
}
func (m *StopServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopServerResponse proto.InternalMessageInfo

type GetServerInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServerInfoRequest) Reset()         { *m = GetServerInfoRequest{} }
func (m *GetServerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetServerInfoRequest) ProtoMessage()    {}
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{29}
}

func (m *GetServerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServerInfoRequest.Unmarshal(m, b)
}
func (m *GetServerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServerInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetServerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServerInfoRequest.Merge(m, src)
}
func (m *GetServerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetServerInfoRequest.Size(m)
}
func (m *GetServerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServerInfoRequest proto.InternalMessageInfo

type ServerInfo struct {
	ServerName           *ServerName `protobuf:"bytes,1,req,name=server_name,json=serverName" json:"server_name,omitempty"`
	WebuiPort            *uint32     `protobuf:"varint,2,opt,name=webui_port,json=webuiPort" json:"webui_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{30}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetServerName() *ServerName {
	if m != nil {
		return m.ServerName
	}
	return nil
}

func (m *ServerInfo) GetWebuiPort() uint32 {
	if m != nil && m.WebuiPort != nil {
		return *m.WebuiPort
	}
	return 0
}

type GetServerInfoResponse struct {
	ServerInfo           *ServerInfo `protobuf:"bytes,1,req,name=server_info,json=serverInfo" json:"server_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetServerInfoResponse) Reset()         { *m = GetServerInfoResponse{} }
func (m *GetServerInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetServerInfoResponse) ProtoMessage()    {}
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{31}
}

func (m *GetServerInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServerInfoResponse.Unmarshal(m, b)
}
func (m *GetServerInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServerInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetServerInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServerInfoResponse.Merge(m, src)
}
func (m *GetServerInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetServerInfoResponse.Size(m)
}
func (m *GetServerInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServerInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServerInfoResponse proto.InternalMessageInfo

func (m *GetServerInfoResponse) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type UpdateConfigurationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigurationRequest) Reset()         { *m = UpdateConfigurationRequest{} }
func (m *UpdateConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigurationRequest) ProtoMessage()    {}
func (*UpdateConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{32}
}

func (m *UpdateConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigurationRequest.Unmarshal(m, b)
}
func (m *UpdateConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigurationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigurationRequest.Merge(m, src)
}
func (m *UpdateConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigurationRequest.Size(m)
}
func (m *UpdateConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigurationRequest proto.InternalMessageInfo

type UpdateConfigurationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigurationResponse) Reset()         { *m = UpdateConfigurationResponse{} }
func (m *UpdateConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigurationResponse) ProtoMessage()    {}
func (*UpdateConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8bee81a31f1f5, []int{33}
}

func (m *UpdateConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigurationResponse.Unmarshal(m, b)
}
func (m *UpdateConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigurationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigurationResponse.Merge(m, src)
}
func (m *UpdateConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigurationResponse.Size(m)
}
func (m *UpdateConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigurationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.GetRegionInfoResponse_CompactionState", GetRegionInfoResponse_CompactionState_name, GetRegionInfoResponse_CompactionState_value)
	proto.RegisterEnum("pb.OpenRegionResponse_RegionOpeningState", OpenRegionResponse_RegionOpeningState_name, OpenRegionResponse_RegionOpeningState_value)
	proto.RegisterType((*GetRegionInfoRequest)(nil), "pb.GetRegionInfoRequest")
	proto.RegisterType((*GetRegionInfoResponse)(nil), "pb.GetRegionInfoResponse")
	proto.RegisterType((*GetStoreFileRequest)(nil), "pb.GetStoreFileRequest")
	proto.RegisterType((*GetStoreFileResponse)(nil), "pb.GetStoreFileResponse")
	proto.RegisterType((*GetOnlineRegionRequest)(nil), "pb.GetOnlineRegionRequest")
	proto.RegisterType((*GetOnlineRegionResponse)(nil), "pb.GetOnlineRegionResponse")
	proto.RegisterType((*OpenRegionRequest)(nil), "pb.OpenRegionRequest")
	proto.RegisterType((*OpenRegionRequest_RegionOpenInfo)(nil), "pb.OpenRegionRequest.RegionOpenInfo")
	proto.RegisterType((*OpenRegionResponse)(nil), "pb.OpenRegionResponse")
	proto.RegisterType((*WarmupRegionRequest)(nil), "pb.WarmupRegionRequest")
	proto.RegisterType((*WarmupRegionResponse)(nil), "pb.WarmupRegionResponse")
	proto.RegisterType((*CloseRegionRequest)(nil), "pb.CloseRegionRequest")
	proto.RegisterType((*CloseRegionResponse)(nil), "pb.CloseRegionResponse")
	proto.RegisterType((*FlushRegionRequest)(nil), "pb.FlushRegionRequest")
	proto.RegisterType((*FlushRegionResponse)(nil), "pb.FlushRegionResponse")
	proto.RegisterType((*SplitRegionRequest)(nil), "pb.SplitRegionRequest")
	proto.RegisterType((*SplitRegionResponse)(nil), "pb.SplitRegionResponse")
	proto.RegisterType((*CompactRegionRequest)(nil), "pb.CompactRegionRequest")
	proto.RegisterType((*CompactRegionResponse)(nil), "pb.CompactRegionResponse")
	proto.RegisterType((*UpdateFavoredNodesRequest)(nil), "pb.UpdateFavoredNodesRequest")
	proto.RegisterType((*UpdateFavoredNodesRequest_RegionUpdateInfo)(nil), "pb.UpdateFavoredNodesRequest.RegionUpdateInfo")
	proto.RegisterType((*UpdateFavoredNodesResponse)(nil), "pb.UpdateFavoredNodesResponse")
	proto.RegisterType((*MergeRegionsRequest)(nil), "pb.MergeRegionsRequest")
	proto.RegisterType((*MergeRegionsResponse)(nil), "pb.MergeRegionsResponse")
	proto.RegisterType((*WALEntry)(nil), "pb.WALEntry")
	proto.RegisterType((*ReplicateWALEntryRequest)(nil), "pb.ReplicateWALEntryRequest")
	proto.RegisterType((*ReplicateWALEntryResponse)(nil), "pb.ReplicateWALEntryResponse")
	proto.RegisterType((*RollWALWriterRequest)(nil), "pb.RollWALWriterRequest")
	proto.RegisterType((*RollWALWriterResponse)(nil), "pb.RollWALWriterResponse")
	proto.RegisterType((*StopServerRequest)(nil), "pb.StopServerRequest")
	proto.RegisterType((*StopServerResponse)(nil), "pb.StopServerResponse")
	proto.RegisterType((*GetServerInfoRequest)(nil), "pb.GetServerInfoRequest")
	proto.RegisterType((*ServerInfo)(nil), "pb.ServerInfo")
	proto.RegisterType((*GetServerInfoResponse)(nil), "pb.GetServerInfoResponse")
	proto.RegisterType((*UpdateConfigurationRequest)(nil), "pb.UpdateConfigurationRequest")
	proto.RegisterType((*UpdateConfigurationResponse)(nil), "pb.UpdateConfigurationResponse")
}

func init() { proto.RegisterFile("Admin.proto", fileDescriptor_5da8bee81a31f1f5) }

var fileDescriptor_5da8bee81a31f1f5 = []byte{
	// 1713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5f, 0x6f, 0x23, 0x49,
	0x11, 0xbf, 0xb1, 0x93, 0x5c, 0x5c, 0xb1, 0x13, 0x6f, 0x3b, 0x7f, 0xbc, 0xde, 0x5d, 0x6e, 0x19,
	0xa1, 0x23, 0xc7, 0x81, 0x91, 0x72, 0x3a, 0x09, 0x71, 0xb0, 0xe0, 0xfc, 0xdb, 0x64, 0x37, 0x6b,
	0x47, 0xe3, 0x70, 0x11, 0x2b, 0xa4, 0x51, 0xdb, 0xee, 0xb1, 0x9b, 0x1d, 0x4f, 0xcf, 0x76, 0xb7,
	0xb3, 0xf2, 0x3b, 0x0f, 0x08, 0xf1, 0xc2, 0x13, 0x8f, 0xf0, 0x09, 0xf8, 0x02, 0xbc, 0xf3, 0x2d,
	0x78, 0xe5, 0x99, 0x8f, 0x80, 0xfa, 0x8f, 0xed, 0x19, 0xcf, 0x38, 0x0b, 0xe4, 0x6d, 0xba, 0xaa,
	0xba, 0xaa, 0xba, 0xba, 0xea, 0x57, 0xd5, 0x03, 0x5b, 0xad, 0xc1, 0x98, 0x46, 0xcd, 0x98, 0x33,
	0xc9, 0x50, 0x21, 0xee, 0x35, 0xb6, 0x2e, 0x8e, 0xb1, 0x20, 0x86, 0xd0, 0x28, 0xdd, 0xb6, 0xae,
	0xcc, 0xa7, 0x1b, 0xc1, 0xee, 0x4b, 0x22, 0x3d, 0x32, 0xa4, 0x2c, 0xba, 0x8c, 0x02, 0xe6, 0x91,
	0xf7, 0x13, 0x22, 0x24, 0xfa, 0x12, 0x36, 0xb8, 0x26, 0xd6, 0x9d, 0xe7, 0x85, 0xc3, 0xad, 0xa3,
	0x5a, 0x33, 0xee, 0x35, 0x8d, 0x58, 0x37, 0x26, 0x7d, 0x1a, 0x50, 0xc2, 0x3d, 0x2b, 0x82, 0xbe,
	0x80, 0x6a, 0x9f, 0x8d, 0x63, 0xdc, 0x97, 0x94, 0x45, 0xbe, 0x90, 0x58, 0x92, 0x7a, 0xe1, 0xb9,
	0x73, 0xb8, 0xe9, 0xed, 0x2c, 0xe8, 0x5d, 0x45, 0x76, 0xff, 0x50, 0x80, 0xbd, 0x25, 0x83, 0x22,
	0x66, 0x91, 0x20, 0xe8, 0xc7, 0xb0, 0x65, 0xd4, 0xf9, 0x34, 0x0a, 0x98, 0x35, 0xbb, 0xbd, 0x30,
	0xab, 0x85, 0x81, 0xcf, 0xbf, 0xd1, 0xcd, 0x0a, 0xab, 0xdb, 0x47, 0x5f, 0xa8, 0x5d, 0xb9, 0x56,
	0x9a, 0x27, 0x69, 0x7f, 0x32, 0x0e, 0x22, 0x17, 0xca, 0x54, 0x78, 0xa4, 0xcf, 0xee, 0x08, 0xa7,
	0xd1, 0xb0, 0x5e, 0xd4, 0xe7, 0x48, 0xd1, 0xdc, 0x73, 0xd8, 0x59, 0xd2, 0x83, 0x36, 0x61, 0xad,
	0xdd, 0x69, 0x9f, 0x55, 0x3f, 0x41, 0x25, 0x58, 0x7f, 0x73, 0xd9, 0xee, 0x78, 0x55, 0x47, 0x7f,
	0xb6, 0x5e, 0x75, 0xbc, 0x6a, 0x01, 0xd5, 0x60, 0x47, 0x7f, 0xfa, 0xad, 0xf6, 0xa9, 0x6f, 0xf8,
	0x45, 0xf7, 0x2d, 0xd4, 0x5e, 0x12, 0xd9, 0x95, 0x8c, 0x93, 0x73, 0x1a, 0x92, 0xff, 0x2b, 0xf6,
	0xfb, 0xb0, 0x11, 0xe0, 0x31, 0x0d, 0xa7, 0xf5, 0xc2, 0xf3, 0xe2, 0x61, 0xd9, 0xb3, 0x2b, 0xf7,
	0x6b, 0x7d, 0xb1, 0x09, 0xdd, 0x36, 0xcc, 0xcf, 0x00, 0x84, 0x22, 0xfa, 0x01, 0x0d, 0x49, 0xdd,
	0x79, 0x5e, 0x3c, 0x2c, 0x79, 0x25, 0x31, 0x13, 0x73, 0xeb, 0xb0, 0xff, 0x92, 0xc8, 0x4e, 0x14,
	0xd2, 0x88, 0x18, 0x93, 0xd6, 0x2b, 0xf7, 0x15, 0x1c, 0x64, 0x38, 0xab, 0xae, 0xae, 0x78, 0xff,
	0xd5, 0xb9, 0x7f, 0x2e, 0xc2, 0xa3, 0x4e, 0x4c, 0xa2, 0x94, 0x05, 0xd4, 0x82, 0x12, 0x8b, 0x49,
	0x4a, 0xc9, 0xf7, 0x94, 0x92, 0x8c, 0xa4, 0x55, 0xab, 0xe8, 0x5a, 0xf5, 0x26, 0xb3, 0x5f, 0xe8,
	0x10, 0x76, 0x04, 0xe1, 0x77, 0x84, 0x77, 0x25, 0xe6, 0xf2, 0x84, 0x0d, 0x4c, 0x4a, 0xac, 0x79,
	0xcb, 0x64, 0xf4, 0x43, 0x40, 0x63, 0x2c, 0x24, 0xe1, 0xbe, 0x98, 0x0a, 0x49, 0xc6, 0xbe, 0xa4,
	0x63, 0x52, 0x5f, 0xd7, 0xc2, 0x55, 0xc3, 0xe9, 0x6a, 0xc6, 0x0d, 0x1d, 0x93, 0xc6, 0xbf, 0x1c,
	0xd8, 0x4e, 0x1b, 0x45, 0x9f, 0x2f, 0xdd, 0xd2, 0xf2, 0x79, 0x67, 0x17, 0xf4, 0x35, 0x1c, 0xdc,
	0x11, 0x2e, 0x54, 0x74, 0x58, 0xe0, 0xb3, 0x20, 0x50, 0x01, 0xf4, 0xa3, 0x99, 0x6b, 0x15, 0x6f,
	0xd7, 0xb2, 0x3b, 0x41, 0xc7, 0x30, 0xdb, 0xca, 0xbf, 0xaf, 0xa0, 0x12, 0xe0, 0x3b, 0xc6, 0xc9,
	0x40, 0xcb, 0x8a, 0x7a, 0x71, 0x11, 0xd5, 0xae, 0x3e, 0x4b, 0x1b, 0x8f, 0x89, 0x57, 0xb6, 0x42,
	0x6a, 0x8f, 0x40, 0xbf, 0x84, 0x27, 0x2a, 0x14, 0xe7, 0x8c, 0x9f, 0x52, 0x21, 0x39, 0xed, 0x4d,
	0x24, 0x19, 0x5c, 0xb1, 0xa1, 0x47, 0xe2, 0x10, 0x4f, 0xeb, 0x6b, 0x3a, 0x97, 0xef, 0x13, 0x71,
	0xff, 0xe6, 0x00, 0x4a, 0xc6, 0xdb, 0xde, 0x70, 0x1b, 0x2a, 0x6a, 0x17, 0x8d, 0x86, 0xb6, 0xd0,
	0xd4, 0xf5, 0xd8, 0x42, 0xcb, 0x8a, 0x27, 0xee, 0x87, 0x46, 0x43, 0x53, 0x68, 0x65, 0x96, 0x58,
	0xb9, 0x17, 0x80, 0xb2, 0x32, 0x08, 0x60, 0xa3, 0x73, 0x7d, 0xd6, 0x3e, 0x3b, 0xad, 0x7e, 0x82,
	0x10, 0x6c, 0xb7, 0xae, 0xbc, 0xb3, 0xd6, 0xe9, 0xaf, 0x7d, 0x4b, 0x73, 0x14, 0xed, 0xbc, 0x75,
	0x79, 0x75, 0x76, 0xaa, 0x49, 0x97, 0xed, 0x97, 0xd5, 0x82, 0x7b, 0x06, 0xb5, 0x5b, 0xcc, 0xc7,
	0x93, 0x38, 0x9d, 0x4b, 0x4d, 0x48, 0xe4, 0xdb, 0xc7, 0xc1, 0xc4, 0xdd, 0x87, 0xdd, 0xb4, 0x1a,
	0x73, 0x12, 0xf7, 0x4f, 0x05, 0x40, 0x27, 0x21, 0x13, 0xe9, 0x62, 0xf8, 0xdf, 0x4a, 0x34, 0x9d,
	0x01, 0xfd, 0x90, 0x09, 0x15, 0xc7, 0xdc, 0x0c, 0x38, 0x31, 0x4c, 0x9d, 0x01, 0x4d, 0xa8, 0x4a,
	0x8e, 0x23, 0x41, 0xa5, 0xa9, 0x2c, 0xff, 0xed, 0x6b, 0x83, 0x46, 0x3f, 0x5d, 0x93, 0x7c, 0x42,
	0xbc, 0xed, 0x05, 0xf7, 0x32, 0x7a, 0xfb, 0x1a, 0xfd, 0x1c, 0xd0, 0x80, 0x08, 0x49, 0x23, 0x6c,
	0x00, 0x51, 0x27, 0x89, 0xbe, 0xf3, 0x6c, 0xda, 0x3c, 0x4a, 0x48, 0x1a, 0x72, 0x5e, 0xe9, 0xac,
	0xe7, 0x96, 0x8e, 0xfb, 0x23, 0xa8, 0xa5, 0x42, 0x62, 0x73, 0x64, 0x1f, 0x36, 0xd4, 0xd9, 0xc8,
	0x40, 0xc7, 0x64, 0xd3, 0xb3, 0x2b, 0xf7, 0x2f, 0x0e, 0xa0, 0xf3, 0x70, 0x22, 0x46, 0x0f, 0x08,
	0xe1, 0xf7, 0xa1, 0x4a, 0x03, 0x9f, 0x85, 0x03, 0xc2, 0x7d, 0x39, 0xc2, 0x91, 0x2f, 0x85, 0x2d,
	0xec, 0x0a, 0x0d, 0x3a, 0x8a, 0x7c, 0x33, 0xc2, 0xd1, 0x8d, 0x40, 0x5f, 0xc1, 0xfe, 0x07, 0x4e,
	0x25, 0xf1, 0x03, 0x65, 0xd1, 0xff, 0x80, 0x43, 0x7f, 0x8c, 0xf9, 0x3b, 0xc2, 0x2d, 0x90, 0xd7,
	0x34, 0x57, 0xbb, 0x73, 0x8b, 0xc3, 0x37, 0x9a, 0xe5, 0xfe, 0xd1, 0x81, 0x5a, 0xca, 0x43, 0x7b,
	0xa2, 0xcf, 0x61, 0x27, 0xc4, 0x42, 0x5a, 0x5d, 0x1a, 0x20, 0x94, 0xaf, 0x6b, 0x5e, 0x45, 0x91,
	0xf5, 0x0e, 0x85, 0x0e, 0xa8, 0x0e, 0x9f, 0x6a, 0x11, 0x32, 0xb0, 0x6d, 0x6f, 0xb6, 0x34, 0xee,
	0xb0, 0x7b, 0xdd, 0x61, 0x19, 0x77, 0x7a, 0x80, 0xba, 0x71, 0x48, 0xe5, 0x03, 0xe2, 0xf5, 0x19,
	0x6c, 0x09, 0xa5, 0xc2, 0x8f, 0x19, 0x8d, 0xa4, 0xf6, 0xaa, 0xec, 0x81, 0x26, 0x5d, 0x2b, 0x8a,
	0xbb, 0x07, 0xb5, 0x94, 0x0d, 0x9b, 0xee, 0xef, 0x61, 0xd7, 0x76, 0xb6, 0x07, 0x18, 0xdf, 0x85,
	0xf5, 0x31, 0xfe, 0x2d, 0xe3, 0x36, 0x18, 0x66, 0x91, 0x68, 0x54, 0x45, 0xed, 0xcd, 0xac, 0x51,
	0x1d, 0xc0, 0xde, 0x92, 0x49, 0xeb, 0xcb, 0x3f, 0x1d, 0x78, 0xfc, 0xab, 0x78, 0x80, 0x25, 0x39,
	0x4f, 0x60, 0xdc, 0xcc, 0xa3, 0x0e, 0x6c, 0x4d, 0x34, 0x33, 0xd9, 0x2e, 0x9a, 0xca, 0xad, 0x95,
	0x7b, 0xac, 0xc3, 0x86, 0x6f, 0x10, 0x60, 0x32, 0xff, 0x6e, 0x30, 0xa8, 0x2e, 0xf3, 0xff, 0x6b,
	0x8c, 0xcf, 0x80, 0x75, 0xe1, 0xe3, 0x60, 0xed, 0xfe, 0x04, 0x1a, 0x79, 0xae, 0xda, 0xdc, 0x6b,
	0xc0, 0x26, 0xb7, 0xdf, 0x75, 0x47, 0xa3, 0xc4, 0x7c, 0xed, 0xfe, 0xc3, 0x81, 0xda, 0x1b, 0xc2,
	0x87, 0xb6, 0x02, 0xc5, 0x02, 0xf4, 0x36, 0x6d, 0x1f, 0xc6, 0xf7, 0xdd, 0xd3, 0xa7, 0x46, 0xa8,
	0x95, 0x90, 0xef, 0xd5, 0x0b, 0x1f, 0x95, 0x3f, 0x46, 0xdf, 0x85, 0xcd, 0x80, 0xf1, 0x3e, 0xed,
	0x85, 0xc4, 0x22, 0xd1, 0x7a, 0x80, 0x43, 0x41, 0xbc, 0x39, 0x79, 0x45, 0x5b, 0x5d, 0xcb, 0x6f,
	0xab, 0x0a, 0x75, 0xd3, 0xe7, 0xb0, 0x07, 0xfc, 0x9d, 0x03, 0x9b, 0xb7, 0xad, 0xab, 0xb3, 0x48,
	0xf2, 0x29, 0x7a, 0x0a, 0xc5, 0x77, 0x64, 0x6a, 0x0f, 0x04, 0xca, 0xc1, 0xdb, 0xd6, 0xd5, 0x6b,
	0x32, 0xf5, 0x14, 0x59, 0xd5, 0xe8, 0x3b, 0x32, 0xf5, 0xef, 0x70, 0x38, 0x21, 0x7e, 0x6f, 0x2a,
	0x6d, 0xf0, 0xcb, 0x5e, 0xe5, 0x1d, 0x99, 0x7e, 0xab, 0xa8, 0xc7, 0x8a, 0x88, 0x8e, 0x60, 0x0f,
	0x0b, 0xc1, 0xfa, 0x14, 0x4b, 0x32, 0xf0, 0xfb, 0x24, 0x0c, 0xfd, 0x3e, 0x9b, 0x44, 0x52, 0x1f,
	0x64, 0xdd, 0xab, 0x2d, 0x98, 0x27, 0x24, 0x0c, 0x4f, 0x14, 0xcb, 0xfd, 0xb7, 0x03, 0x75, 0xd5,
	0x17, 0x69, 0x1f, 0x4b, 0x32, 0xf3, 0x67, 0x16, 0x6c, 0x17, 0xd6, 0x89, 0x5a, 0xdb, 0xd4, 0x2b,
	0x5b, 0xc7, 0x8c, 0x8c, 0x61, 0xa1, 0x23, 0xd8, 0xe5, 0x76, 0x3f, 0x65, 0xd1, 0x49, 0x38, 0x51,
	0xe7, 0xbf, 0x34, 0x28, 0x51, 0xf2, 0x72, 0x79, 0xe8, 0x05, 0x34, 0x04, 0x9b, 0xf0, 0x3e, 0x51,
	0x03, 0xbb, 0x4a, 0x1b, 0x11, 0xe3, 0x3e, 0x39, 0xa5, 0xfc, 0x1a, 0xcb, 0x91, 0xf6, 0xb6, 0xe4,
	0xdd, 0x23, 0x81, 0x7e, 0x06, 0x8f, 0x0d, 0xf7, 0x42, 0x0d, 0x74, 0x2d, 0xde, 0x1f, 0xd1, 0xbb,
	0xf9, 0xf6, 0x35, 0xbd, 0x7d, 0xb5, 0x80, 0xfb, 0x04, 0x1e, 0xe7, 0x9c, 0xd8, 0x5e, 0xcb, 0x3e,
	0xec, 0x7a, 0x2c, 0x0c, 0x6f, 0x5b, 0x57, 0xb7, 0x0a, 0x45, 0xf9, 0x6c, 0x34, 0xfc, 0x05, 0xec,
	0x2d, 0xd1, 0x17, 0x00, 0x6a, 0x13, 0x4c, 0x32, 0x03, 0x81, 0x3a, 0x5a, 0x65, 0xaf, 0x62, 0xc8,
	0x37, 0x4c, 0x43, 0x9f, 0xfb, 0x25, 0x3c, 0xea, 0x4a, 0x16, 0x9b, 0x52, 0x99, 0x05, 0x78, 0x5f,
	0x15, 0x1f, 0x16, 0xb6, 0xf8, 0x4a, 0x9e, 0x5d, 0xb9, 0xbb, 0x80, 0x92, 0xc2, 0x0b, 0xdf, 0xd4,
	0xbc, 0xab, 0x89, 0x89, 0x87, 0x8c, 0xfb, 0x1b, 0x80, 0x05, 0x51, 0x4d, 0xaa, 0xa6, 0x9b, 0xf9,
	0x11, 0xb6, 0x68, 0x9e, 0x2d, 0x53, 0x10, 0xf3, 0x6f, 0x35, 0x2e, 0x7f, 0x20, 0xbd, 0x09, 0xf5,
	0x63, 0xc6, 0xa5, 0x6d, 0xd7, 0x25, 0x4d, 0xb9, 0x66, 0x5c, 0xba, 0x17, 0xfa, 0x35, 0x93, 0xb4,
	0xba, 0x18, 0x89, 0xad, 0xa1, 0xe5, 0xd7, 0x4c, 0x42, 0xd8, 0x1a, 0xd2, 0x03, 0xc8, 0xd3, 0x19,
	0x1a, 0x9c, 0xb0, 0x28, 0xa0, 0xc3, 0x09, 0xd7, 0x69, 0x31, 0x3b, 0xc5, 0x33, 0x78, 0x92, 0xcb,
	0x35, 0xd6, 0x8e, 0xfe, 0x5e, 0x82, 0xb2, 0x7e, 0xf1, 0x29, 0xe5, 0xb4, 0x4f, 0xd0, 0x29, 0x54,
	0x52, 0xef, 0x1f, 0x54, 0xcf, 0x79, 0x12, 0x69, 0xd5, 0x8d, 0xc7, 0x2b, 0x1f, 0x4b, 0xa8, 0x05,
	0xe5, 0xe4, 0x1b, 0x02, 0x1d, 0x58, 0xd1, 0xe5, 0x17, 0x4b, 0xa3, 0x9e, 0x65, 0x58, 0x15, 0xaf,
	0x60, 0x67, 0xe9, 0xd5, 0x80, 0x1a, 0x56, 0x38, 0xe7, 0x91, 0xd1, 0x78, 0x92, 0xcb, 0xb3, 0xba,
	0xbe, 0x01, 0x58, 0xcc, 0x9a, 0x68, 0x2f, 0xf7, 0x69, 0xd0, 0xd8, 0xcf, 0x1f, 0x49, 0xd5, 0x59,
	0x92, 0x03, 0x9e, 0x39, 0x4b, 0xce, 0xe4, 0x68, 0xce, 0x92, 0x37, 0x0b, 0xa2, 0x17, 0xb0, 0x95,
	0x98, 0x7b, 0x90, 0xb6, 0x94, 0x9d, 0x0d, 0x1b, 0x07, 0x19, 0xfa, 0x62, 0x7f, 0x62, 0xca, 0x30,
	0xfb, 0xb3, 0x83, 0x91, 0xd9, 0x9f, 0x37, 0x8e, 0xbc, 0x80, 0xad, 0x44, 0xcf, 0x36, 0xfb, 0xb3,
	0x83, 0x82, 0xd9, 0x9f, 0xd3, 0xdc, 0x55, 0x52, 0xa4, 0x3a, 0xad, 0x49, 0x8a, 0xbc, 0x7e, 0x6f,
	0x92, 0x22, 0xb7, 0x2d, 0xab, 0x40, 0x26, 0x31, 0xdb, 0x04, 0x32, 0xa7, 0x1b, 0x99, 0x40, 0xe6,
	0xc1, 0x3b, 0xba, 0x86, 0x47, 0x19, 0x90, 0x41, 0x4f, 0x4d, 0xeb, 0xc9, 0x47, 0xdb, 0xc6, 0xb3,
	0x15, 0x5c, 0xab, 0xf1, 0x0c, 0x36, 0xcc, 0x03, 0xe6, 0x61, 0x6a, 0x4e, 0xa1, 0x92, 0x02, 0x32,
	0x13, 0xa1, 0x3c, 0xcc, 0x33, 0x11, 0xca, 0x47, 0x3d, 0x53, 0x7c, 0x09, 0xd4, 0x99, 0x97, 0xc7,
	0x32, 0x3a, 0xcd, 0x8b, 0x2f, 0x07, 0x41, 0xbe, 0x01, 0x58, 0xc0, 0x9c, 0xc9, 0xf6, 0x0c, 0x46,
	0x9a, 0x6c, 0xcf, 0xa2, 0x21, 0xea, 0x02, 0xca, 0xce, 0x16, 0xe8, 0xd9, 0xbd, 0xe3, 0x51, 0xe3,
	0x3b, 0xab, 0xd8, 0x56, 0xe9, 0xb7, 0x50, 0xcb, 0x01, 0x21, 0x94, 0xd8, 0x96, 0x87, 0x5d, 0x8d,
	0xcf, 0x56, 0xf2, 0x8d, 0xde, 0xe3, 0x16, 0xfc, 0x80, 0xf1, 0x61, 0x13, 0xc7, 0xb8, 0x3f, 0x22,
	0xcd, 0x11, 0x1e, 0x30, 0x16, 0x37, 0x47, 0xbd, 0xf9, 0xff, 0xaa, 0xde, 0x24, 0x68, 0x0e, 0x49,
	0x44, 0xb8, 0xea, 0xce, 0xc7, 0xe6, 0xd7, 0xd6, 0xb5, 0x62, 0x88, 0x0b, 0xe7, 0xf7, 0x8e, 0xf3,
	0x57, 0xc7, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x01, 0xcf, 0x8a, 0xf0, 0x12, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetRegionInfo(ctx context.Context, in *GetRegionInfoRequest, opts ...grpc.CallOption) (*GetRegionInfoResponse, error)
	GetStoreFile(ctx context.Context, in *GetStoreFileRequest, opts ...grpc.CallOption) (*GetStoreFileResponse, error)
	GetOnlineRegion(ctx context.Context, in *GetOnlineRegionRequest, opts ...grpc.CallOption) (*GetOnlineRegionResponse, error)
	OpenRegion(ctx context.Context, in *OpenRegionRequest, opts ...grpc.CallOption) (*OpenRegionResponse, error)
	WarmupRegion(ctx context.Context, in *WarmupRegionRequest, opts ...grpc.CallOption) (*WarmupRegionResponse, error)
	CloseRegion(ctx context.Context, in *CloseRegionRequest, opts ...grpc.CallOption) (*CloseRegionResponse, error)
	FlushRegion(ctx context.Context, in *FlushRegionRequest, opts ...grpc.CallOption) (*FlushRegionResponse, error)
	SplitRegion(ctx context.Context, in *SplitRegionRequest, opts ...grpc.CallOption) (*SplitRegionResponse, error)
	CompactRegion(ctx context.Context, in *CompactRegionRequest, opts ...grpc.CallOption) (*CompactRegionResponse, error)
	MergeRegions(ctx context.Context, in *MergeRegionsRequest, opts ...grpc.CallOption) (*MergeRegionsResponse, error)
	ReplicateWALEntry(ctx context.Context, in *ReplicateWALEntryRequest, opts ...grpc.CallOption) (*ReplicateWALEntryResponse, error)
	Replay(ctx context.Context, in *ReplicateWALEntryRequest, opts ...grpc.CallOption) (*ReplicateWALEntryResponse, error)
	RollWALWriter(ctx context.Context, in *RollWALWriterRequest, opts ...grpc.CallOption) (*RollWALWriterResponse, error)
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	StopServer(ctx context.Context, in *StopServerRequest, opts ...grpc.CallOption) (*StopServerResponse, error)
	UpdateFavoredNodes(ctx context.Context, in *UpdateFavoredNodesRequest, opts ...grpc.CallOption) (*UpdateFavoredNodesResponse, error)
	UpdateConfiguration(ctx context.Context, in *UpdateConfigurationRequest, opts ...grpc.CallOption) (*UpdateConfigurationResponse, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetRegionInfo(ctx context.Context, in *GetRegionInfoRequest, opts ...grpc.CallOption) (*GetRegionInfoResponse, error) {
	out := new(GetRegionInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/GetRegionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetStoreFile(ctx context.Context, in *GetStoreFileRequest, opts ...grpc.CallOption) (*GetStoreFileResponse, error) {
	out := new(GetStoreFileResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/GetStoreFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetOnlineRegion(ctx context.Context, in *GetOnlineRegionRequest, opts ...grpc.CallOption) (*GetOnlineRegionResponse, error) {
	out := new(GetOnlineRegionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/GetOnlineRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) OpenRegion(ctx context.Context, in *OpenRegionRequest, opts ...grpc.CallOption) (*OpenRegionResponse, error) {
	out := new(OpenRegionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/OpenRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) WarmupRegion(ctx context.Context, in *WarmupRegionRequest, opts ...grpc.CallOption) (*WarmupRegionResponse, error) {
	out := new(WarmupRegionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/WarmupRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CloseRegion(ctx context.Context, in *CloseRegionRequest, opts ...grpc.CallOption) (*CloseRegionResponse, error) {
	out := new(CloseRegionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/CloseRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) FlushRegion(ctx context.Context, in *FlushRegionRequest, opts ...grpc.CallOption) (*FlushRegionResponse, error) {
	out := new(FlushRegionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/FlushRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SplitRegion(ctx context.Context, in *SplitRegionRequest, opts ...grpc.CallOption) (*SplitRegionResponse, error) {
	out := new(SplitRegionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/SplitRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CompactRegion(ctx context.Context, in *CompactRegionRequest, opts ...grpc.CallOption) (*CompactRegionResponse, error) {
	out := new(CompactRegionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/CompactRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) MergeRegions(ctx context.Context, in *MergeRegionsRequest, opts ...grpc.CallOption) (*MergeRegionsResponse, error) {
	out := new(MergeRegionsResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/MergeRegions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ReplicateWALEntry(ctx context.Context, in *ReplicateWALEntryRequest, opts ...grpc.CallOption) (*ReplicateWALEntryResponse, error) {
	out := new(ReplicateWALEntryResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/ReplicateWALEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Replay(ctx context.Context, in *ReplicateWALEntryRequest, opts ...grpc.CallOption) (*ReplicateWALEntryResponse, error) {
	out := new(ReplicateWALEntryResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/Replay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RollWALWriter(ctx context.Context, in *RollWALWriterRequest, opts ...grpc.CallOption) (*RollWALWriterResponse, error) {
	out := new(RollWALWriterResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/RollWALWriter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/GetServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StopServer(ctx context.Context, in *StopServerRequest, opts ...grpc.CallOption) (*StopServerResponse, error) {
	out := new(StopServerResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/StopServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateFavoredNodes(ctx context.Context, in *UpdateFavoredNodesRequest, opts ...grpc.CallOption) (*UpdateFavoredNodesResponse, error) {
	out := new(UpdateFavoredNodesResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/UpdateFavoredNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateConfiguration(ctx context.Context, in *UpdateConfigurationRequest, opts ...grpc.CallOption) (*UpdateConfigurationResponse, error) {
	out := new(UpdateConfigurationResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminService/UpdateConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	GetRegionInfo(context.Context, *GetRegionInfoRequest) (*GetRegionInfoResponse, error)
	GetStoreFile(context.Context, *GetStoreFileRequest) (*GetStoreFileResponse, error)
	GetOnlineRegion(context.Context, *GetOnlineRegionRequest) (*GetOnlineRegionResponse, error)
	OpenRegion(context.Context, *OpenRegionRequest) (*OpenRegionResponse, error)
	WarmupRegion(context.Context, *WarmupRegionRequest) (*WarmupRegionResponse, error)
	CloseRegion(context.Context, *CloseRegionRequest) (*CloseRegionResponse, error)
	FlushRegion(context.Context, *FlushRegionRequest) (*FlushRegionResponse, error)
	SplitRegion(context.Context, *SplitRegionRequest) (*SplitRegionResponse, error)
	CompactRegion(context.Context, *CompactRegionRequest) (*CompactRegionResponse, error)
	MergeRegions(context.Context, *MergeRegionsRequest) (*MergeRegionsResponse, error)
	ReplicateWALEntry(context.Context, *ReplicateWALEntryRequest) (*ReplicateWALEntryResponse, error)
	Replay(context.Context, *ReplicateWALEntryRequest) (*ReplicateWALEntryResponse, error)
	RollWALWriter(context.Context, *RollWALWriterRequest) (*RollWALWriterResponse, error)
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	StopServer(context.Context, *StopServerRequest) (*StopServerResponse, error)
	UpdateFavoredNodes(context.Context, *UpdateFavoredNodesRequest) (*UpdateFavoredNodesResponse, error)
	UpdateConfiguration(context.Context, *UpdateConfigurationRequest) (*UpdateConfigurationResponse, error)
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_GetRegionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetRegionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/GetRegionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetRegionInfo(ctx, req.(*GetRegionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetStoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/GetStoreFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStoreFile(ctx, req.(*GetStoreFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetOnlineRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetOnlineRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/GetOnlineRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetOnlineRegion(ctx, req.(*GetOnlineRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_OpenRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).OpenRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/OpenRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).OpenRegion(ctx, req.(*OpenRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_WarmupRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmupRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).WarmupRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/WarmupRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).WarmupRegion(ctx, req.(*WarmupRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CloseRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CloseRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/CloseRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CloseRegion(ctx, req.(*CloseRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_FlushRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).FlushRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/FlushRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).FlushRegion(ctx, req.(*FlushRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SplitRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SplitRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/SplitRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SplitRegion(ctx, req.(*SplitRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CompactRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CompactRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/CompactRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CompactRegion(ctx, req.(*CompactRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_MergeRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).MergeRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/MergeRegions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).MergeRegions(ctx, req.(*MergeRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ReplicateWALEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateWALEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ReplicateWALEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/ReplicateWALEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ReplicateWALEntry(ctx, req.(*ReplicateWALEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Replay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateWALEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Replay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/Replay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Replay(ctx, req.(*ReplicateWALEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RollWALWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollWALWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RollWALWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/RollWALWriter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RollWALWriter(ctx, req.(*RollWALWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/GetServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StopServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StopServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/StopServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StopServer(ctx, req.(*StopServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateFavoredNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFavoredNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateFavoredNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/UpdateFavoredNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateFavoredNodes(ctx, req.(*UpdateFavoredNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminService/UpdateConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateConfiguration(ctx, req.(*UpdateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegionInfo",
			Handler:    _AdminService_GetRegionInfo_Handler,
		},
		{
			MethodName: "GetStoreFile",
			Handler:    _AdminService_GetStoreFile_Handler,
		},
		{
			MethodName: "GetOnlineRegion",
			Handler:    _AdminService_GetOnlineRegion_Handler,
		},
		{
			MethodName: "OpenRegion",
			Handler:    _AdminService_OpenRegion_Handler,
		},
		{
			MethodName: "WarmupRegion",
			Handler:    _AdminService_WarmupRegion_Handler,
		},
		{
			MethodName: "CloseRegion",
			Handler:    _AdminService_CloseRegion_Handler,
		},
		{
			MethodName: "FlushRegion",
			Handler:    _AdminService_FlushRegion_Handler,
		},
		{
			MethodName: "SplitRegion",
			Handler:    _AdminService_SplitRegion_Handler,
		},
		{
			MethodName: "CompactRegion",
			Handler:    _AdminService_CompactRegion_Handler,
		},
		{
			MethodName: "MergeRegions",
			Handler:    _AdminService_MergeRegions_Handler,
		},
		{
			MethodName: "ReplicateWALEntry",
			Handler:    _AdminService_ReplicateWALEntry_Handler,
		},
		{
			MethodName: "Replay",
			Handler:    _AdminService_Replay_Handler,
		},
		{
			MethodName: "RollWALWriter",
			Handler:    _AdminService_RollWALWriter_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _AdminService_GetServerInfo_Handler,
		},
		{
			MethodName: "StopServer",
			Handler:    _AdminService_StopServer_Handler,
		},
		{
			MethodName: "UpdateFavoredNodes",
			Handler:    _AdminService_UpdateFavoredNodes_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _AdminService_UpdateConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Admin.proto",
}
